// Troisième vague d'enrichissement — 30 plantes + 14 associations.
// Même schéma que data-sup.js (ESCOP, OMS, Wood, monographies européennes).

export const PLANTES_SUP2 = [
  {
    id: "aigremoine",
    nom: "Aigremoine",
    latin: "Agrimonia eupatoria",
    famille: "Rosacées",
    image: null,
    emoji: "🌾",
    bienfaits: ["Digestion", "Antiseptique", "Cicatrisant", "Toux"],
    parties: "Sommités fleuries",
    usages: "Diarrhée légère, angine, toux enrouée, cicatrisation des plaies.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour ; en gargarisme pour la gorge.",
    actifs: "Tanins (8–10 %), flavonoïdes, triterpènes, acide ellagique.",
    formes: "Infusion, teinture-mère, gargarisme, cataplasme.",
    posologie: "2 à 3 g par tasse, 2 à 3 fois par jour ; gargarisme concentré 3 fois par jour.",
    interactions: "Les tanins réduisent l'absorption du fer : boire à distance des repas.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Cures courtes conseillées (tanins irritants à long terme)."
  },
  {
    id: "aneth",
    nom: "Aneth",
    latin: "Anethum graveolens",
    famille: "Apiacées",
    image: null,
    emoji: "🌿",
    bienfaits: ["Digestion", "Ballonnements", "Antispasmodique", "Sommeil"],
    parties: "Graines, Feuilles",
    usages: "Ballonnements, coliques du nourrisson (par la mère allaitante), digestion lente.",
    preparation: "Infusion de graines écrasées 10 min, après les repas.",
    actifs: "Huile essentielle (carvone 30–60 %, limonène), flavonoïdes.",
    formes: "Infusion, graines à mâcher, HE (avis professionnel).",
    posologie: "1 à 2 tasses par jour après les repas (1,5 g de graines).",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Doses culinaires OK ; doses thérapeutiques déconseillées.",
    precaution: "HE photosensibilisante ; prudence chez l'enfant."
  },
  {
    id: "anserine",
    nom: "Anserine (patte d'oie)",
    latin: "Potentilla anserina",
    famille: "Rosacées",
    image: null,
    emoji: "🦢",
    bienfaits: ["Digestion", "Antispasmodique", "Cicatrisant", "Nerfs"],
    parties: "Feuilles, Racine",
    usages: "Diarrhée spasmodique, douleurs menstruelles, plaies, dysménorrhée.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour.",
    actifs: "Tanins, flavonoïdes, procyanidines, mucilages.",
    formes: "Infusion, teinture, cataplasme.",
    posologie: "2 à 3 g par tasse, jusqu'à 3 fois par jour.",
    interactions: "Tanins : espacer des traitements oraux de 2 h.",
    grossesse: "Déconseillée (historiquement emménagogue à fortes doses).",
    precaution: "Cures courtes ; ne pas cumuler avec d'autres riches en tanins."
  },
  {
    id: "aspérule",
    nom: "Aspérule odorante",
    latin: "Galium odoratum",
    famille: "Rubiacées",
    image: null,
    emoji: "⭐",
    bienfaits: ["Sommeil", "Nerfs", "Drainage", "Circulation"],
    parties: "Parties aériennes",
    usages: "Nervosité, insomnie légère, antispasmodique doux, boissons estivales.",
    preparation: "Macérat à froid (coumarine fragile à la chaleur), 1 c. à soupe par litre.",
    actifs: "Coumarine (0,03–0,1 %), mélilotoside, acide ascorbique.",
    formes: "Macérat froid, sirop, vin aromatisé.",
    posologie: "1 à 2 verres par jour de macérat froid, cures courtes de 2 semaines.",
    interactions: "Prudence avec les anticoagulants (la coumarine est antivitamine K).",
    grossesse: "Déconseillée.",
    precaution: "Ne jamais dépasser les doses usuelles (coumarine hépatotoxique à forte dose)."
  },
  {
    id: "avocatier",
    nom: "Avocatier (feuilles)",
    latin: "Persea americana",
    famille: "Lauracées",
    image: null,
    emoji: "🥑",
    bienfaits: ["Tension artérielle", "Drainage", "Foie", "Cholestérol"],
    parties: "Feuilles",
    usages: "Hypertension légère, rétention d'eau, drainage hépatique, confort digestif.",
    preparation: "Infusion de feuilles séchées 10 min, 2 tasses par jour.",
    actifs: "Flavonoïdes, tanins, terpènes, acides gras (huile de pulpe).",
    formes: "Infusion, teinture, huile de pulpe (alimentaire).",
    posologie: "1,5 à 2 g de feuilles par tasse, 2 fois par jour.",
    interactions: "Potentialise les antihypertenseurs (surveillance).",
    grossesse: "Déconseillée en infusion thérapeutique.",
    precaution: "Éviter en association avec la prise d'anticoagulants."
  },
  {
    id: "basilic-sacre",
    nom: "Basilic sacré (tulsi)",
    latin: "Ocimum tenuiflorum",
    famille: "Lamiacées",
    image: null,
    emoji: "🪷",
    bienfaits: ["Immunité", "Nerfs", "Drainage", "Antioxydant"],
    parties: "Feuilles, Parties aériennes",
    usages: "Stress chronique, immunité affaiblie, toux, drainage léger, adaptogène.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour, ou extrait standardisé.",
    actifs: "Ursolic acid, eugénol, acide rosmarinique, flavonoïdes.",
    formes: "Infusion, poudre (churna), extrait standardisé (2,5 % acide ursolique).",
    posologie: "2 à 3 tasses par jour ; extrait : 300 à 600 mg/j.",
    interactions: "Prudence avec les anticoagulants et antidiabétiques.",
    grossesse: "Déconseillé à doses thérapeutiques (effet utérotonique possible).",
    precaution: "Peut abaisser la glycémie : surveillance des diabétiques."
  },
  {
    id: "baume-coffre",
    nom: "Baume du Canada",
    latin: "Populus balsamifera",
    famille: "Salicacées",
    image: null,
    emoji: "🕯️",
    bienfaits: ["Antiseptique", "Toux", "Cicatrisant", "Décongestionnant"],
    parties: "Bourgeons (gemmothérapie)",
    usages: "Bronchite, sinusite, catarrhe, plaies lentes, galactogène traditionnel.",
    preparation: "Macérat glycériné de bourgeons, baume externe pour la poitrine.",
    actifs: "Résines balsamiques, salicine, populoside, flavonoïdes.",
    formes: "Macérat glycériné, baume externe, teinture.",
    posologie: "Macérat glycériné : 5 à 15 gouttes par jour selon l'usage.",
    interactions: "Prudence avec les salicylés (sensibilité aspirine).",
    grossesse: "Déconseillé sans avis.",
    precaution: "Usage externe : test allergique préalable (résines)."
  },
  {
    id: "bistorte",
    nom: "Bistorte",
    latin: "Persicaria bistorta",
    famille: "Polygonacées",
    image: null,
    emoji: "🌺",
    bienfaits: ["Cicatrisant", "Antiseptique", "Digestion", "Toux"],
    parties: "Racine",
    usages: "Diarrhée, leucorrhées, plaies, saignements légers, gargarismes.",
    preparation: "Décoction de racine 15 min, en usage interne ou externe.",
    actifs: "Tanins (15–20 %), gallotanins, acides phénoliques.",
    formes: "Décoction, gargarisme, cataplasme, teinture.",
    posologie: "1 à 2 g de racine par tasse, 2 fois par jour (cure courte).",
    interactions: "Tanins : espacer de 2 h des médicaments.",
    grossesse: "Déconseillée à doses thérapeutiques.",
    precaution: "Constipation possible en usage prolongé."
  },
  {
    id: "bois-bandé",
    nom: "Bois bandé (muira puama)",
    latin: "Ptychopetalum olacoides",
    famille: "Olacacées",
    image: null,
    emoji: "🪵",
    bienfaits: ["Tonique", "Nerfs", "Mémoire", "Surrénales"],
    parties: "Écorce, Racine",
    usages: "Fatigue générale, asthénie nerveuse, tonus intellectuel, vitalité.",
    preparation: "Teinture-mère de l'écorce, 20 à 40 gouttes matin et midi.",
    actifs: "Alcaloïdes (muirapuanine), triterpènes, lignanes, flavonoïdes.",
    formes: "Teinture-mère, gélules d'extrait sec.",
    posologie: "1 à 1,5 g/j d'extrait sec, ou 40 gouttes de teinture 2 fois par jour.",
    interactions: "Prudence avec les antihypertenseurs (peut stimuler).",
    grossesse: "Déconseillé.",
    precaution: "Éviter le soir (stimulant) et en hypertension non contrôlée."
  },
  {
    id: "bourdaine",
    nom: "Bourdaine",
    latin: "Rhamnus frangula",
    famille: "Rhamnacées",
    image: null,
    emoji: "🪶",
    bienfaits: ["Digestion", "Drainage", "Diurétique", "Antiseptique"],
    parties: "Écorce (séchée 1 an)",
    usages: "Constipation occasionnelle, transit paresseux (laxatif stimulant doux).",
    preparation: "Décoction d'écorce 15 min (jamais fraîche : irritante).",
    actifs: "Anthraquinones (franguline, émodine), tanins.",
    formes: "Décoction, poudre encapsulée, teinture.",
    posologie: "0,5 à 2 g/j d'écorce sèche, le soir, cures courtes de 8 à 10 jours maximum.",
    interactions: "Espace 2 h avec tout autre médicament (laxatif accélérant).",
    grossesse: "CONTRE-INDIQUÉE (stimulant utérin).",
    precaution: "Jamais en usage prolongé (dépendance du transit) ; contre-indiquée en cas de colite."
  },
  {
    id: "buplevre",
    nom: "Buplèvre",
    latin: "Bupleurum chinense",
    famille: "Apiacées",
    image: null,
    emoji: "🌿",
    bienfaits: ["Foie", "Nerfs", "Drainage", "Humeur"],
    parties: "Racine",
    usages: "Congestion hépatique, stress, humeur variable, troubles hormonaux légers (MTCC).",
    preparation: "Décoction de racine 20 min ou extrait standardisé.",
    actifs: "Saïkosaponines (a, d), polysaccharides, acides oléanoliques.",
    formes: "Décoction, extrait sec standardisé, formules TCM (Xiao Yao San).",
    posologie: "3 à 9 g/j de racine sèche en décoction, cures de 3 semaines.",
    interactions: "Prudence avec les immunosuppresseurs et corticoïdes.",
    grossesse: "Déconseillé sans avis TCM.",
    precaution: "Troubles digestifs légers possibles ; prudence hépatique à fortes doses."
  },
  {
    id: "caféier",
    nom: "Caféier (vert)",
    latin: "Coffea arabica",
    famille: "Rubiacées",
    image: null,
    emoji: "☕",
    bienfaits: ["Tonique", "Mémoire", "Circulation", "Cholestérol"],
    parties: "Graines vertes non torréfiées",
    usages: "Fatigue passagère, vigilance, métabolisme, glycémie (extrait vert).",
    preparation: "Extrait standardisé en gélules, décoction de graines vertes.",
    actifs: "Caféine (2–3 %), acide chlorogénique (6–10 %), trigonelline.",
    formes: "Gélules d'extrait de graines vertes, décoction.",
    posologie: "100 à 200 mg/j d'extrait standardisé à 45 % d'acide chlorogénique.",
    interactions: "Réduit l'absorption du fer ; prudence avec les hypoglycémiants et antihypertenseurs.",
    grossesse: "Max 200 mg/j de caféine (café + extraits).",
    precaution: "Insomnie, anxiété, palpitations : éviter le soir."
  },
  {
    id: "cameline",
    nom: "Cameline",
    latin: "Camelina sativa",
    famille: "Brassicacées",
    image: null,
    emoji: "🌼",
    bienfaits: ["Cœur", "Cholestérol", "Anti-inflammatoire", "Peau"],
    parties: "Graines (huile)",
    usages: "Santé cardiovasculaire, équilibre oméga-3, peau sèche, cholestérol.",
    preparation: "Huile de cameline à froid, 1 à 2 c. à soupe par jour (assaisonnement).",
    actifs: "Acide alpha-linolénique (oméga-3 30–38 %), vitamine E.",
    formes: "Huile alimentaire à froid, gélules.",
    posologie: "1 à 2 c. à soupe par jour en assaisonnement (jamais chauffer).",
    interactions: "Prudence avec les anticoagulants (forte dose oméga-3).",
    grossesse: "Autorisée (source alimentaire oméga-3 précieuse).",
    precaution: "Huile fragile : conserver au froid à l'abri de la lumière."
  },
  {
    id: "cardamome",
    nom: "Cardamome",
    latin: "Elettaria cardamomum",
    famille: "Zingibéracées",
    image: null,
    emoji: "🫧",
    bienfaits: ["Digestion", "Ballonnements", "Antiseptique", "Nerfs"],
    parties: "Graines",
    usages: "Ballonnements, digestion lente, halitose, café moins irritant.",
    preparation: "Infusion de graines écrasées 10 min, ou graines à mâcher.",
    actifs: "Huile essentielle (acétate de terpinyle, 1,8-cinéole, limonène).",
    formes: "Infusion, graines à mâcher, poudre en cuisine.",
    posologie: "2 à 3 graines à mâcher après le repas, ou 1 tasse d'infusion.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée aux doses culinaires.",
    precaution: "Très bien tolérée ; calculs biliaires : éviter les fortes doses."
  },
  {
    id: "cascara",
    nom: "Cascara (bourdaine d'Amérique)",
    latin: "Rhamnus purshiana",
    famille: "Rhamnacées",
    image: null,
    emoji: "🪵",
    bienfaits: ["Digestion", "Drainage", "Diurétique", "Antiseptique"],
    parties: "Écorce (séchée 1 an)",
    usages: "Constipation occasionnelle résistante aux laxatifs doux.",
    preparation: "Décoction d'écorce le soir (effet le lendemain matin).",
    actifs: "Anthraquinones (cascarosides A, B), émodine.",
    formes: "Décoction, gélules d'écorce, teinture.",
    posologie: "20 à 30 mg/j d'anthraninoïdes totaux, le soir, 8 à 10 jours maximum.",
    interactions: "Espace 2 h des autres médicaments ; risque d'hypokaliémie en usage prolongé.",
    grossesse: "CONTRE-INDIQUÉE.",
    precaution: "Jamais plus de 10 jours ; colopathie, obstruction : interdit."
  },
  {
    id: "céleri",
    nom: "Céleri",
    latin: "Apium graveolens",
    famille: "Apiacées",
    image: null,
    emoji: "🥬",
    bienfaits: ["Drainage", "Diurétique", "Articulations", "Tension artérielle"],
    parties: "Graines, Feuilles, Racine",
    usages: "Rétention d'eau, arthrose, goutte, hypertension légère, digestion.",
    preparation: "Infusion de graines 10 min ; céleri-rave et feuilles en alimentation.",
    actifs: "APIIN, limonène, phthalides (3-n-butylphtalide), flavonoïdes.",
    formes: "Infusion, teinture, aliment cru.",
    posologie: "1 à 2 g de graines par tasse, 2 fois par jour.",
    interactions: "Potentialise les diurétiques et anticoagulants ; prudence lithium.",
    grossesse: "Doses culinaires OK ; infusions thérapeutiques déconseillées.",
    precaution: "Allergie aux Apiacées fréquente (réactions croisées bouleau-céleri)."
  },
  {
    id: "chamomille-allemande",
    nom: "Camomille allemande (teinture)",
    latin: "Matricaria recutita (TM)",
    famille: "Astéracées",
    image: null,
    emoji: "🌻",
    bienfaits: ["Digestion", "Cicatrisant", "Anxiété", "Peau"],
    parties: "Fleurs (teinture-mère)",
    usages: "Gastrite, ulcère, colopathie, plaies, aphtes, nervosité.",
    preparation: "Teinture-mère : 20 à 30 gouttes dans un peu d'eau 3 fois par jour.",
    actifs: "Apigénine, α-bisabolol, chamazulène (concentrés en teinture).",
    formes: "Teinture-mère, gélules d'extrait standardisé.",
    posologie: "20 à 30 gouttes de teinture 3 fois par jour, avant les repas.",
    interactions: "Prudence avec les anticoagulants à forte dose.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Allergie aux Astéracées : éviter."
  },
  {
    id: "chanvre",
    nom: "Chanvre (graines)",
    latin: "Cannabis sativa (graines)",
    famille: "Cannabacées",
    image: null,
    emoji: "🌱",
    bienfaits: ["Peau", "Cœur", "Cholestérol", "Anti-inflammatoire"],
    parties: "Graines (huile, protéines)",
    usages: "Équilibre oméga-3/oméga-6, peau sèche, eczéma, nutrition sportive.",
    preparation: "Huile de chanvre à froid, graines décortiquées, protéine en poudre.",
    actifs: "Acides gras oméga-3/6 (ratio idéal 1:3), protéines complètes, vitamine E.",
    formes: "Huile alimentaire, graines, protéine en poudre.",
    posologie: "1 à 2 c. à soupe d'huile par jour en assaisonnement.",
    interactions: "Pas d'interaction connue (aucun CBD/THC dans les graines).",
    grossesse: "Autorisée (alimentaire).",
    precaution: "Huile fragile : au frais, jamais chauffée."
  },
  {
    id: "chondroitine",
    nom: "Chondroïtine (concombre de mer)",
    latin: "Holothuria (chondroïtine marine)",
    famille: "Holothuriidés",
    image: null,
    emoji: "🪸",
    bienfaits: ["Articulations", "Anti-inflammatoire", "Peau", "Circulation"],
    parties: "Extrait de concombre de mer",
    usages: "Arthrose, confort articulaire, hydratation cutanée, circulation.",
    preparation: "Complément alimentaire en gélules, associé à la glucosamine.",
    actifs: "Chondroïtine sulfate, glycosaminoglycanes, peptides marins.",
    formes: "Gélules, poudre.",
    posologie: "800 à 1 200 mg/j de chondroïtine sulfate, en cure de 3 mois.",
    interactions: "Prudence avec les anticoagulants.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Allergie aux produits marins : éviter."
  },
  {
    id: "cimicifuga",
    nom: "Actée à grappes noires",
    latin: "Actaea racemosa",
    famille: "Renonculacées",
    image: null,
    emoji: "🖤",
    bienfaits: ["Bouffées de chaleur", "Humeur", "Sommeil", "Antispasmodique"],
    parties: "Racine",
    usages: "Bouffées de chaleur ménopausiques, humeur variable, troubles du sommeil.",
    preparation: "Extrait sec standardisé en gélules, teinture-mère.",
    actifs: "Triterpènes glycosides (actéine), alcaloïdes isoquinoléiques, acides phénoliques.",
    formes: "Extrait standardisé (Remifemin 6,5 %), teinture-mère.",
    posologie: "20 à 80 mg/j d'extrait standardisé, cures de 3 à 6 mois.",
    interactions: "Prudence avec les médicaments hépatotoxiques (rares hépatites signalées).",
    grossesse: "CONTRE-INDIQUÉE.",
    precaution: "Surveillance hépatique en usage prolongé ; éviter en antécédent de cancer hormonodépendant."
  },
  {
    id: "citron",
    nom: "Citron",
    latin: "Citrus limon",
    famille: "Rutacées",
    image: null,
    emoji: "🍋",
    bienfaits: ["Drainage", "Immunité", "Digestion", "Circulation"],
    parties: "Jus, Zeste",
    usages: "Drainage hépatique matin, défenses immunitaires, digestion, circulation.",
    preparation: "Jus d'un demi-citron dans 200 ml d'eau tiède, à jeun.",
    actifs: "Vitamine C, acide citrique, flavonoïdes (hespéridine), limonène.",
    formes: "Jus frais, zeste râpé, HE du zeste.",
    posologie: "1 demi-citron par jour à jeun ; zeste bio râpé en cuisine.",
    interactions: "Peut potentialiser certains médicaments (CYP3A4, limonène).",
    grossesse: "Autorisé.",
    precaution: "Émail dentaire : rincer la bouche après ; reflux : boire tiède en petites gorgées."
  },
  {
    id: "coing",
    nom: "Coing",
    latin: "Cydonia oblonga",
    famille: "Rosacées",
    image: null,
    emoji: "🍐",
    bienfaits: ["Digestion", "Estomac", "Toux", "Cicatrisant"],
    parties: "Fruit (mucilages), Graines",
    usages: "Diarrhée, gastrite, toux sèche, aphtes, gêne digestive estivale.",
    preparation: "Gelée de coing artisanale, macérat de graines (usage externe).",
    actifs: "Mucilages (graines), pectines, tanins.",
    formes: "Gelée, compote, macérat de graines en cataplasme.",
    posologie: "1 à 2 c. à soupe de gelée par jour ; compote de coing cuite.",
    interactions: "Espace 2 h des médicaments.",
    grossesse: "Autorisé.",
    precaution: "Graines non consommées crues (amygdaline)."
  },
  {
    id: "consoude",
    nom: "Consoude (externe)",
    latin: "Symphytum officinale",
    famille: "Boraginacées",
    image: null,
    emoji: "🩹",
    bienfaits: ["Cicatrisant", "Anti-inflammatoire", "Articulations", "Nerfs"],
    parties: "Racine, Feuilles (USAGE EXTERNE UNIQUEMENT)",
    usages: "Entorses, contusions, tendinites, douleurs articulaires localisées.",
    preparation: "Pommade de racine, cataplasme de feuilles fraîches.",
    actifs: "Allantoïne, mucilages, acide rosmarinique, APE (alcaloïdes pyrrolizidiniques).",
    formes: "Pommade, crème (allantoin 5 %), cataplasme.",
    posologie: "Application 2 fois par jour sur peau intacte, max 10 jours.",
    interactions: "Jamais sur plaie ouverte (AP toxiques passent dans le sang).",
    grossesse: "Déconseillée même en usage externe étendu.",
    precaution: "USAGE EXTERNE UNIQUEMENT et sur peau saine, courtes cures."
  },
  {
    id: "coriandre",
    nom: "Coriandre",
    latin: "Coriandrum sativum",
    famille: "Apiacées",
    image: null,
    emoji: "🍃",
    bienfaits: ["Digestion", "Ballonnements", "Antiseptique", "Drainage"],
    parties: "Graines, Feuilles",
    usages: "Ballonnements, digestion lente, drainage des métaux lourds (chéloration douce).",
    preparation: "Infusion de graines écrasées 10 min, après les repas.",
    actifs: "Huile essentielle (linalol 60–70 %), flavonoïdes, polyphénols.",
    formes: "Infusion, graines en cuisine, HE (avis professionnel).",
    posologie: "1 à 2 tasses par jour après les repas (1,5 g de graines).",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée aux doses culinaires.",
    precaution: "Allergie aux Apiacées possible."
  },
  {
    id: "cumin",
    nom: "Cumin",
    latin: "Cuminum cyminum",
    famille: "Apiacées",
    image: null,
    emoji: "🫘",
    bienfaits: ["Digestion", "Ballonnements", "Antispasmodique", "Immunité"],
    parties: "Graines",
    usages: "Ballonnements, digestion des légumineuses, spasmes digestifs, carminatif.",
    preparation: "Infusion de graines écrasées 10 min, après le repas.",
    actifs: "Huile essentielle (cuminaldéhyde 30–40 %), flavonoïdes.",
    formes: "Infusion, graines en cuisine, poudre.",
    posologie: "1 tasse après le repas (1 g de graines écrasées).",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée aux doses culinaires.",
    precaution: "Photosensibilisation possible (HE) ; bien toléré en alimentaire."
  },
  {
    id: "curry",
    nom: "Mélange curry (feuilles)",
    latin: "Murraya koenigii",
    famille: "Rutacées",
    image: null,
    emoji: "🍛",
    bienfaits: ["Digestion", "Antioxydant", "Foie", "Immunité"],
    parties: "Feuilles",
    usages: "Digestion, antioxydant global, soutien hépatique, glycémie.",
    preparation: "Infusion de feuilles fraîches ou séchées 10 min, en cuisine.",
    actifs: "Carbazole alcaloïdes, huile essentielle (β-caryophyllène), flavonoïdes.",
    formes: "Infusion, feuilles fraîches en cuisine, poudre.",
    posologie: "1 tasse par jour, ou quelques feuilles fraîches dans les plats.",
    interactions: "Prudence avec les antidiabétiques.",
    grossesse: "Autorisée aux doses culinaires.",
    precaution: "Peu documenté à fortes doses : rester aux doses usuelles."
  },
  {
    id: "echinopanax",
    nom: "Ginseng sibérien (variété)",
    latin: "Eleutherococcus senticosus (var.)",
    famille: "Araliacées",
    image: null,
    emoji: "🌲",
    bienfaits: ["Surrénales", "Immunité", "Mémoire", "Tonique"],
    parties: "Racine",
    usages: "Adaptogène doux, fatigue physique et intellectuelle, immunité, sportifs.",
    preparation: "Teinture-mère ou extrait sec standardisé.",
    actifs: "Éleuthérosides B et E, polysaccharides.",
    formes: "Teinture-mère, gélules d'extrait standardisé.",
    posologie: "300 à 600 mg/j d'extrait standardisé, le matin, cures de 3 semaines.",
    interactions: "Prudence avec digoxine, antidiabétiques, antihypertenseurs.",
    grossesse: "Déconseillé.",
    precaution: "Éviter le soir (stimulant)."
  },
  {
    id: "elsholtzia",
    nom: "Elsholtzia",
    latin: "Elsholtzia ciliata",
    famille: "Lamiacées",
    image: null,
    emoji: "🌾",
    bienfaits: ["Décongestionnant", "Antiseptique", "Immunité", "Digestion"],
    parties: "Parties aériennes",
    usages: "Rhinite, sinusite, grippe (TCM), nausées estivales, digestion.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour en phase aiguë.",
    actifs: "Huile essentielle (élsholtzicétone), flavonoïdes, tanins.",
    formes: "Infusion, teinture.",
    posologie: "2 à 3 tasses par jour, cures courtes de 5 jours.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Prudence, peu documentée.",
    precaution: "Bien tolérée aux doses usuelles."
  },
  {
    id: "epilobe",
    nom: "Épilobe",
    latin: "Epilobium parviflorum",
    famille: "Onagracées",
    image: null,
    emoji: "🌸",
    bienfaits: ["Drainage", "Diurétique", "Antiseptique", "Prostate"],
    parties: "Parties aériennes",
    usages: "Troubles urinaires masculins, hypertrophie bénigne de la prostate, cystite.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour, cures de 3 semaines.",
    actifs: "Flavonoïdes, tanins, acides phénoliques, β-sitostérol.",
    formes: "Infusion, teinture, gélules d'extrait sec.",
    posologie: "2 à 3 g par tasse, 2 à 3 fois par jour, cures de 3 semaines.",
    interactions: "Prudence avec les traitements diurétiques.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Rien de notable aux doses normales ; toute affection prostatique nécessite un avis médical."
  },
  {
    id: "fenouil-marine",
    nom: "Fenouil marin (crithme)",
    latin: "Crithmum maritimum",
    famille: "Apiacées",
    image: null,
    emoji: "🌊",
    bienfaits: ["Drainage", "Digestion", "Diurétique", "Circulation"],
    parties: "Feuilles, Tiges (gemmothérapie)",
    usages: "Drainage rénal, rétention d'eau, cellulite, digestion, circulation.",
    preparation: "Macérat glycériné de jeunes pousses, infusion des feuilles.",
    actifs: "Huile essentielle (limonène, thymol méthyl-éther), sels minéraux, flavonoïdes.",
    formes: "Macérat glycériné, infusion, alimentaire (condiment).",
    posologie: "Macérat glycériné : 5 à 15 gouttes matin et midi.",
    interactions: "Potentialise les diurétiques.",
    grossesse: "Déconseillé en macérat concentré.",
    precaution: "Bien hydrater ; allergie aux Apiacées possible."
  },
  {
    id: "fucus",
    nom: "Fucus (algue brune)",
    latin: "Fucus vesiculosus",
    famille: "Fucacées",
    image: null,
    emoji: "🫧",
    bienfaits: ["Drainage", "Tonique", "Digestion", "Circulation"],
    parties: "Thalle",
    usages: "Soutien métabolique, minceur (satietogène), apport en iode, fatigue.",
    preparation: "Poudre de thalle en gélules, décoction douce 10 min.",
    actifs: "Iode (0,03–0,11 %), alginates, fucoïdanes, polyphénols.",
    formes: "Gélules de poudre, teinture-mère, alimentaire.",
    posologie: "1 à 2 g/j de poudre de thalle, cures de 3 à 4 semaines.",
    interactions: "MAJEUR : interfère avec les médicaments thyroïdiens ; attention aux anticoagulants.",
    grossesse: "CONTRE-INDIQUÉ (excès d'iode).",
    precaution: "Thyropathie : interdit sans avis médical ; surveiller l'apport en iode global."
  },
  {
    id: "gentiane",
    nom: "Gentiane jaune",
    latin: "Gentiana lutea",
    famille: "Gentianacées",
    image: null,
    emoji: "💛",
    bienfaits: ["Digestion", "Tonique", "Estomac", "Foie"],
    parties: "Racine",
    usages: "Apathie digestive, appétit capricieux, digestion lente, asthénie.",
    preparation: "Macérat à froid (amerfragile), 20 gouttes avant les repas.",
    actifs: "Amers iridoïdes (gentiopicrine, amarogentine : plus amer connu), alcaloïdes.",
    formes: "Macérat froid, teinture, vin de gentiane.",
    posologie: "20 à 30 gouttes de teinture dans un peu d'eau, 15 min avant les repas.",
    interactions: "Prudence avec les antihypertenseurs (élevage possible de la tension).",
    grossesse: "Déconseillée (amers utérotoniques).",
    precaution: "Hypertension, ulcère : éviter ; ne pas boire en cas de gastrite aiguë."
  },
  {
    id: "gingembre-sauvage",
    nom: "Asarum (gingembre sauvage)",
    latin: "Asarum europaeum",
    famille: "Aristolochiacées",
    image: null,
    emoji: "🫚",
    bienfaits: ["Toux", "Antiseptique", "Digestion", "Drainage"],
    parties: "Racine (usage historique)",
    usages: "Toux productive ancienne, émétique léger, purgatif traditionnel.",
    preparation: "Historique : usage TCM encadré uniquement.",
    actifs: "Huile essentielle (asarone), acide aristolochique (toxique).",
    formes: "Historique uniquement : NE PAS UTILISER sans encadrement professionnel.",
    posologie: "Ne pas utiliser en automédication.",
    interactions: "HÉPATOTOXIQUE ET NÉPHROTOXIQUE (acide aristolochique).",
    grossesse: "CONTRE-INDIQUÉ.",
    precaution: "⚠ TOXIQUE : néphrotoxicité et carcinogénicité démontrées. Mentionné à titre historique."
  },
  {
    id: "graviola",
    nom: "Graviola (corossol)",
    latin: "Annona muricata",
    famille: "Annonacées",
    image: null,
    emoji: "🍈",
    bienfaits: ["Antioxydant", "Immunité", "Digestion", "Nerfs"],
    parties: "Feuilles, Fruit",
    usages: "Antioxydant, nervosité, confort digestif tropical, immunité.",
    preparation: "Infusion de feuilles 10 min, fruit frais en jus.",
    actifs: "Acétogénines, flavonoïdes, alcaloïdes (annonacine : neurotoxique à forte dose).",
    formes: "Infusion de feuilles, jus de fruit frais.",
    posologie: "1 à 2 tasses par jour, cures courtes de 2 semaines.",
    interactions: "Prudence avec les antihypertenseurs et sédatifs.",
    grossesse: "CONTRE-INDIQUÉE (annonacine).",
    precaution: "Ne pas consommer quotidiennement sur le long terme (risque neurologique documenté aux Antilles)."
  },
  {
    id: "houblon",
    nom: "Houblon",
    latin: "Humulus lupulus",
    famille: "Cannabacées",
    image: null,
    emoji: "🍺",
    bienfaits: ["Sommeil", "Anxiété", "Lactation", "Antiseptique"],
    parties: "Cônes (strobiles)",
    usages: "Insomnie, nervosité, galactogène, aide à l'endormissement.",
    preparation: "Infusion 10 min à couvert (luménone volatile), le soir.",
    actifs: "Luménone, humulone, lupulone, flavonoïdes (xanthohumol).",
    formes: "Infusion, teinture, gélules, oreiller aromatique.",
    posologie: "1 à 2 g par tasse, 1 tasse le soir ; gélules : 250 à 500 mg au coucher.",
    interactions: "Potentialise les sédatifs ; contre-indiqué avec les traitements œstrogéniques.",
    grossesse: "Déconseillé (action œstrogénique-like).",
    precaution: "Somnolence ; allaitement : OK (galactogène), sinon prudence."
  },
  {
    id: "hysope",
    nom: "Hysope",
    latin: "Hyssopus officinalis",
    famille: "Lamiacées",
    image: null,
    emoji: "💙",
    bienfaits: ["Antiseptique", "Toux", "Cicatrisant", "Décongestionnant"],
    parties: "Sommités fleuries",
    usages: "Bronchite, angine, toux productive, cicatrisation des plaies.",
    preparation: "Infusion 10 min à couvert, 2 tasses par jour ; gargarisme concentré.",
    actifs: "Huile essentielle (pinocamphone, pinène), marrubiine, tanins.",
    formes: "Infusion, HE (avis professionnel), cataplasme.",
    posologie: "1 à 2 g par tasse, 2 fois par jour, cures courtes de 5 jours.",
    interactions: "HE : neurotoxique à forte dose ; prudence épilepsie.",
    grossesse: "CONTRE-INDIQUÉE (HE et infusions concentrées).",
    precaution: "HE interdite chez l'enfant, la femme enceinte et l'épileptique."
  },
  {
    id: "icumoe",
    nom: "Ipeca",
    latin: "Cephaelis ipecacuanha",
    famille: "Rubiacées",
    image: null,
    emoji: "🚫",
    bienfaits: ["Toux", "Digestion"],
    parties: "Racine (homéopathie uniquement)",
    usages: "Historique : émétique, homéopathie (toux spasmodique).",
    preparation: "Homéopathie diluée uniquement (au-delà de 3 CH).",
    actifs: "Alcaloïdes (émétine : émétique et toxique à dose brute).",
    formes: "Homéopathie diluée (5 CH et plus).",
    posologie: "Selon praticien homéopathe.",
    interactions: "NE JAMAIS utiliser la racine brute (cardiotoxicité de l'émétine).",
    grossesse: "Homéopathie diluée : selon praticien.",
    precaution: "⚠ TOXIQUE à dose brute : mentionné à titre historique uniquement."
  },
  {
    id: "jasmin",
    nom: "Jasmin",
    latin: "Jasminum officinale",
    famille: "Oléacées",
    image: null,
    emoji: "🤍",
    bienfaits: ["Anxiété", "Sommeil", "Nerfs", "Antispasmodique"],
    parties: "Fleurs",
    usages: "Stress, insomnie nerveuse, tension émotionnelle, aphrodisiaque traditionnel.",
    preparation: "Infusion de fleurs séchées 10 min, le soir.",
    actifs: "Huile essentielle (benzyl acétate, indole), jasmonates, sambunigrine.",
    formes: "Infusion, HE (très coûteuse), thé aromatisé.",
    posologie: "1 tasse le soir (1 g de fleurs séchées).",
    interactions: "Potentialise les sédatifs.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Allergie aux Oléacées possible."
  },
  {
    id: "kudzu",
    nom: "Kudzu",
    latin: "Pueraria lobata",
    famille: "Fabacées",
    image: null,
    emoji: "🪴",
    bienfaits: ["Circulation", "Nerfs", "Cholestérol", "Foie"],
    parties: "Racine",
    usages: "Dépendance à l'alcool (réduction de l'envie), circulation, migration légère.",
    preparation: "Extrait sec standardisé, fécule de kudzu en cuisine.",
    actifs: "Isoflavones (daidzéine, puérarine), daidzine.",
    formes: "Extrait sec standardisé, poudre de racine (kakko-to en TCM).",
    posologie: "500 mg à 1,5 g/j d'extrait standardisé, en cure encadrée.",
    interactions: "MAJEUR : potentialise les anticoagulants et traitements hormonaux ; prudence avec l'alcool.",
    grossesse: "Déconseillé (isoflavones).",
    precaution: "Cancer hormonodépendant : éviter ; concentration possible au volant."
  },
  {
    id: "laitue-vireuse",
    nom: "Laitue vireuse",
    latin: "Lactuca virosa",
    famille: "Astéracées",
    image: null,
    emoji: "🥗",
    bienfaits: ["Sommeil", "Antispasmodique", "Nerfs", "Toux"],
    parties: "Feuilles, Laitex",
    usages: "Insomnie légère, toux nerveuse, spasmes digestifs, antitussif doux.",
    preparation: "Infusion de feuilles séchées 10 min, le soir.",
    actifs: "Lactucarium (lactucine, lactucopicrine), flavonoïdes.",
    formes: "Infusion, teinture, sirop antitussif.",
    posologie: "1 à 2 g par tasse, le soir (effet sédatif léger).",
    interactions: "Potentialise les sédatifs.",
    grossesse: "Déconseillée.",
    precaution: "Ne pas confondre avec la laitue cultivée (effet beaucoup plus léger)."
  },
  {
    id: "linaloe",
    nom: "Linaloe (bois de rose)",
    latin: "Aniba rosaeodora",
    famille: "Lauracées",
    image: null,
    emoji: "🪵",
    bienfaits: ["Anxiété", "Antiseptique", "Peau", "Nerfs"],
    parties: "Bois (huile essentielle)",
    usages: "Stress, anxiété, soins de la peau, cicatrisation douce.",
    preparation: "HE diluée en massage, diffusion douce.",
    actifs: "Linalol (85–95 %), géraniol, acétate de linalyle.",
    formes: "HE en massage dilué, diffusion.",
    posologie: "Massage : 2 à 3 gouttes diluées à 10 % dans une huile végétale.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée en diffusion et massage dilué après le 1er trimestre.",
    precaution: "Espèce protégée : privilégier les huiles certifiées durables."
  },
  {
    id: "lotier",
    nom: "Lotier corniculé",
    latin: "Lotus corniculatus",
    famille: "Fabacées",
    image: null,
    emoji: "🌞",
    bienfaits: ["Nerfs", "Antispasmodique", "Sommeil", "Digestion"],
    parties: "Sommités fleuries",
    usages: "Nervosité, spasmes digestifs, insomnie légère, expectorant doux.",
    preparation: "Infusion 10 min, 1 à 2 tasses par jour, le soir de préférence.",
    actifs: "Flavonoïdes, tanins, traces de coumarines.",
    formes: "Infusion, teinture.",
    posologie: "1 à 2 g par tasse, 2 fois par jour.",
    interactions: "Prudence avec les anticoagulants (coumarines en trace).",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Plante fraîche légèrement toxique (cyanogène) : toujours séchée."
  },
  {
    id: "maïs",
    nom: "Maïs (stigmates)",
    latin: "Zea mays",
    famille: "Poacées",
    image: null,
    emoji: "🌽",
    bienfaits: ["Diurétique", "Drainage", "Tension artérielle", "Circulation"],
    parties: "Stigmates (soies)",
    usages: "Rétention d'eau, cystite, hypertension légère, drainage rénal doux.",
    preparation: "Infusion de stigmates 10 min, 2 à 3 tasses par jour.",
    actifs: "Flavonoïdes (maysine, maysoside), sels de potassium, saponines.",
    formes: "Infusion, teinture, macérat glycériné.",
    posologie: "1,5 à 2 g de stigmates par tasse, jusqu'à 3 fois par jour.",
    interactions: "Potentialise les diurétiques et antihypertenseurs.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Déshydratation possible : bien boire."
  },
  {
    id: "marrube-blanc",
    nom: "Marrube blanc",
    latin: "Marrubium vulgare",
    famille: "Lamiacées",
    image: null,
    emoji: "🤍",
    bienfaits: ["Toux", "Digestion", "Circulation", "Antiseptique"],
    parties: "Sommités fleuries",
    usages: "Toux productive, bronchite, digestion lente, appétit capricieux.",
    preparation: "Infusion 10 min à couvert, 2 à 3 tasses par jour.",
    actifs: "Marrubiine (amer), diterpènes, flavonoïdes, tanins.",
    formes: "Infusion, sirop (toux), teinture.",
    posologie: "1 à 2 g par tasse, jusqu'à 3 fois par jour.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Déconseillée à doses thérapeutiques (éménagogue).",
    precaution: "Amertume marquée ; très bien toléré sinon."
  },
  {
    id: "millefeuille",
    nom: "Millefeuille",
    latin: "Achillea millefolium",
    famille: "Astéracées",
    image: null,
    emoji: "🤍",
    bienfaits: ["Circulation", "Digestion", "Antiseptique", "Drainage"],
    parties: "Sommités fleuries",
    usages: "Circulation veineuse, digestion, règles douloureuses, hémorroïdes.",
    preparation: "Infusion 10 min à couvert, 2 à 3 tasses par jour.",
    actifs: "Huile essentielle (azulène, chamazulène), flavonoïdes, alcaloïdes (achilléine).",
    formes: "Infusion, teinture, macérat huileux, cataplasme.",
    posologie: "1 à 2 g par tasse, 2 à 3 fois par jour.",
    interactions: "Prudence avec les anticoagulants (salicilates en trace).",
    grossesse: "CONTRE-INDIQUÉE (éménagogue).",
    precaution: "Allergie aux Astéracées possible."
  },
  {
    id: "myrtille",
    nom: "Myrtille",
    latin: "Vaccinium myrtillus",
    famille: "Éricacées",
    image: null,
    emoji: "🫐",
    bienfaits: ["Circulation", "Antioxydant", "Immunité", "Peau"],
    parties: "Fruit, Feuilles",
    usages: "Vision (rétine), circulation, antioxydant, diarrhée (fruit sec).",
    preparation: "Infusion de feuilles 10 min ; fruit frais ou séché ; extrait standardisé.",
    actifs: "Anthocyanes (fruit), tanins, acides phénoliques (feuilles).",
    formes: "Extrait standardisé (25 % anthocyanes), fruit séché, infusion de feuilles.",
    posologie: "Vision : 120 à 240 mg/j d'extrait standardisé ; diarrhée : fruits séchés en décoction.",
    interactions: "Prudence avec les anticoagulants à forte dose.",
    grossesse: "Autorisée aux doses alimentaires.",
    precaution: "Feuilles : cures courtes uniquement (tanins)."
  },
  {
    id: "nerprun",
    nom: "Nerprun alaterne",
    latin: "Rhamnus alaternus",
    famille: "Rhamnacées",
    image: null,
    emoji: "🌿",
    bienfaits: ["Drainage", "Digestion", "Diurétique", "Foie"],
    parties: "Écorce (séchée 1 an)",
    usages: "Constipation, drainage hépatique doux, transit paresseux.",
    preparation: "Décoction d'écorce le soir (jamais fraîche).",
    actifs: "Anthraquinones (émidine, chrysophanol), flavonoïdes.",
    formes: "Décoction, poudre encapsulée.",
    posologie: "0,5 à 1,5 g/j d'écorce, le soir, 8 jours maximum.",
    interactions: "Espace 2 h des médicaments.",
    grossesse: "CONTRE-INDIQUÉE.",
    precaution: "Laxatif stimulant : cures courtes ; contre-indiqué en colopathie."
  },
  {
    id: "noyer",
    nom: "Noyer",
    latin: "Juglans regia",
    famille: "Juglandacées",
    image: null,
    emoji: "🌰",
    bienfaits: ["Antiseptique", "Drainage", "Circulation", "Peau"],
    parties: "Feuilles, Brou (noix verte)",
    usages: "Antiseptique intestinal, eczéma, hyperhidrose, circulation, drainage.",
    preparation: "Infusion de feuilles 10 min, 2 tasses par jour ; bains externes.",
    actifs: "Juglone (naphtoquinone), tanins (10–12 %), flavonoïdes.",
    formes: "Infusion, bain externe, teinture, macérat glycériné du brou.",
    posologie: "1,5 à 2 g de feuilles par tasse, 2 fois par jour ; bain : 100 g de feuilles infusées.",
    interactions: "Prudence avec les anticoagulants.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Tanins : espacer des médicaments ; coloration de la peau possible (brou)."
  },
  {
    id: "olivier",
    nom: "Olivier",
    latin: "Olea europaea",
    famille: "Oléacées",
    image: null,
    emoji: "🫒",
    bienfaits: ["Tension artérielle", "Cholestérol", "Drainage", "Antioxydant"],
    parties: "Feuilles",
    usages: "Hypertension légère, cholestérol, glycémie, drainage vasculaire.",
    preparation: "Infusion de feuilles 10 min, 2 tasses par jour ; extrait standardisé.",
    actifs: "Oléuropéine (6–9 %), hydroxytyrosol, apigénine.",
    formes: "Infusion, extrait sec standardisé, teinture-mère.",
    posologie: "Infusion : 1,5 g par tasse, 2 fois par jour ; extrait : 250 à 500 mg/j.",
    interactions: "MAJEUR : potentialise les antihypertenseurs et antidiabétiques (surveillance).",
    grossesse: "Déconseillée à doses thérapeutiques (hypotension possible).",
    precaution: "Hypotension : éviter ; surveiller la glycémie."
  },
  {
    id: "origan",
    nom: "Origan",
    latin: "Origanum vulgare",
    famille: "Lamiacées",
    image: null,
    emoji: "🌿",
    bienfaits: ["Antiseptique", "Immunité", "Digestion", "Décongestionnant"],
    parties: "Sommités fleuries",
    usages: "Infections respiratoires, digestion, antiseptique intestinal, mycoses.",
    preparation: "Infusion 10 min à couvert, 1 à 2 tasses par jour ; HE (avis professionnel).",
    actifs: "Huile essentielle (carvacrol 60 %, thymol), flavonoïdes, acide rosmarinique.",
    formes: "Infusion, HE (capsules gastrorésistantes), condiment.",
    posologie: "Infusion : 1 à 2 g par tasse ; HE : selon praticien (jamais pure).",
    interactions: "Prudence avec les anticoagulants (HE).",
    grossesse: "Infusion modérée OK ; HE déconseillée.",
    precaution: "HE dermocaustique pure : toujours diluer."
  },
  {
    id: "passiflore-synthese",
    nom: "Passiflore incarnata (synergie)",
    latin: "Passiflora incarnata",
    famille: "Passifloracées",
    image: null,
    emoji: "💜",
    bienfaits: ["Anxiété", "Sommeil", "Antispasmodique", "Nerfs"],
    parties: "Parties aériennes",
    usages: "Anxiété, insomnie, sevrage tabagique (compulsion), spasmophilie.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour, dont une le soir.",
    actifs: "Flavonoïdes (vitexine, isovitexine), harmane alcaloïdes, GABA naturel.",
    formes: "Infusion, teinture-mère, gélules, association valériane-houblon.",
    posologie: "2 g par tasse, 2 à 3 fois par jour ; sevrage : 40 gouttes de teinture au besoin.",
    interactions: "Potentialise les sédatifs et anticoagulants à forte dose.",
    grossesse: "Autorisée en infusion modérée.",
    precaution: "Somnolence ; prudence au volant."
  },
  {
    id: "petasite",
    nom: "Pétasite",
    latin: "Petasites hybridus",
    famille: "Astéracées",
    image: null,
    emoji: "🎈",
    bienfaits: ["Maux de tête", "Antispasmodique", "Circulation", "Nerfs"],
    parties: "Racine, Feuilles",
    usages: "Migraine récurrente, céphalées de tension, spasmes digestifs, allergies.",
    preparation: "Extrait standardisé en gélules (PA-free uniquement).",
    actifs: "Pétasines, sesquiterpènes, flavonoïdes.",
    formes: "Extrait standardisé sans alcaloïdes PA (Petasites 50, Petadolex).",
    posologie: "50 à 75 mg/j d'extrait standardisé (pétasines), cures de 3 mois.",
    interactions: "Prudence avec les hépatotoxiques.",
    grossesse: "CONTRE-INDIQUÉE (alcaloïdes PA naturels).",
    precaution: "Utiliser UNIQUEMENT des extraits certifiés sans PA ; jamais la plante brute."
  },
  {
    id: "piloselle",
    nom: "Piloselle",
    latin: "Hieracium pilosella",
    famille: "Astéracées",
    image: null,
    emoji: "🐭",
    bienfaits: ["Drainage", "Diurétique", "Antiseptique", "Circulation"],
    parties: "Parties aériennes",
    usages: "Drainage rénal, rétention d'eau, cystite, cellulite, oligurie.",
    preparation: "Infusion 10 min, 2 tasses par jour, cures de 3 semaines.",
    actifs: "Ombelliférone (coumarine), flavonoïdes, acide chicorique.",
    formes: "Infusion, teinture-mère, gélules.",
    posologie: "1,5 à 2 g par tasse, 2 fois par jour.",
    interactions: "Potentialise les diurétiques et anticoagulants (coumarine).",
    grossesse: "Déconseillée (coumarines).",
    precaution: "Prudence anticoagulants ; bien s'hydrater."
  },
  {
    id: "pin",
    nom: "Pin sylvestre",
    latin: "Pinus sylvestris",
    famille: "Pinacées",
    image: null,
    emoji: "🌲",
    bienfaits: ["Décongestionnant", "Antiseptique", "Toux", "Circulation"],
    parties: "Bourgeons, Huile essentielle",
    usages: "Bronchite, sinusite, congestion respiratoire, rheumatismes (bain).",
    preparation: "Infusion de bourgeons 10 min ; HE en inhalation ; bain de bourgeons.",
    actifs: "Huile essentielle (α-pinène, limonène), résines, vitamine C (bourgeons).",
    formes: "Infusion, HE (inhalation, diffusion), sirop de bourgeons, bain.",
    posologie: "Infusion : 1 à 2 g par tasse ; inhalation : 3 gouttes d'HE dans l'eau chaude.",
    interactions: "HE : prudence asthme.",
    grossesse: "Infusion OK ; HE déconseillée par voie orale.",
    precaution: "HE allergisante possible : tester au préalable."
  },
  {
    id: "plantain-moyen",
    nom: "Plantain moyen",
    latin: "Plantago media",
    famille: "Plantaginacées",
    image: null,
    emoji: "🌱",
    bienfaits: ["Toux", "Estomac", "Cicatrisant", "Allergies"],
    parties: "Feuilles",
    usages: "Toux sèche, gastrite, piqûres d'insectes, muqueuses irritées.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour ; feuille froissée en local.",
    actifs: "Mucilages, aucubine, flavonoïdes, tanins.",
    formes: "Infusion, sirop, cataplasme.",
    posologie: "1,5 à 2 g par tasse, 2 à 3 fois par jour.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisé.",
    precaution: "Très bien toléré."
  },
  {
    id: "prunier",
    nom: "Prunellier (baies)",
    latin: "Prunus spinosa",
    famille: "Rosacées",
    image: null,
    emoji: "🖤",
    bienfaits: ["Drainage", "Diurétique", "Digestion", "Circulation"],
    parties: "Fleurs, Baies, Écorce",
    usages: "Rétention d'eau, transit paresseux, bouche sèche, circulation.",
    preparation: "Infusion de fleurs 10 min ; baies cuites en sirop.",
    actifs: "Flavonoïdes, tanins, acides organiques, anthocyanes (baies).",
    formes: "Infusion de fleurs, sirop de baies, macérat glycériné.",
    posologie: "1 à 2 g de fleurs par tasse, 2 fois par jour.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Baies crues légèrement toxiques (amygdaline) : toujours cuites."
  },
  {
    id: "reine-des-alpes",
    nom: "Gentiane des Alpes (reine)",
    latin: "Gentiana acaulis",
    famille: "Gentianacées",
    image: null,
    emoji: "💙",
    bienfaits: ["Digestion", "Tonique", "Estomac", "Foie"],
    parties: "Racine",
    usages: "Digestion difficile, appétit, asthénie digestive (protégée : usage par extraits).",
    preparation: "Teinture-mère (espèce protégée en nature : extraits certifiés uniquement).",
    actifs: "Amers iridoïdes (gentiopicrine), xanthones.",
    formes: "Teinture-mère, gélules.",
    posologie: "20 gouttes de teinture 15 min avant les repas.",
    interactions: "Prudence antihypertenseurs.",
    grossesse: "Déconseillée.",
    precaution: "Espèce protégée : ne jamais cueillir en nature."
  },
  {
    id: "rhodiola",
    nom: "Rhodiola",
    latin: "Rhodiola rosea",
    famille: "Crassulacées",
    image: null,
    emoji: "🌹",
    bienfaits: ["Surrénales", "Tonique", "Mémoire", "Humeur"],
    parties: "Racine",
    usages: "Stress chronique, fatigue intellectuelle, épuisement, performance cognitive.",
    preparation: "Extrait sec standardisé en gélules, le matin.",
    actifs: "Rosavines (3 %), salidroside (1 %), polyphénols.",
    formes: "Extrait standardisé (SHR-5, WS 1375), teinture.",
    posologie: "200 à 400 mg/j d'extrait standardisé (3 % rosavines), le matin, cures de 4 à 8 semaines.",
    interactions: "Prudence avec les antidépresseurs et stimulants.",
    grossesse: "Déconseillée.",
    precaution: "Éviter le soir (stimulant) ; prudence en bipolarité."
  },
  {
    id: "ronce",
    nom: "Ronce (mûres)",
    latin: "Rubus fruticosus",
    famille: "Rosacées",
    image: null,
    emoji: "🫐",
    bienfaits: ["Digestion", "Cicatrisant", "Drainage", "Antiseptique"],
    parties: "Feuilles, Baies",
    usages: "Diarrhée, angine (gargarisme), plaies, transit, antioxydant.",
    preparation: "Infusion de feuilles 10 min, 2 à 3 tasses par jour ; gargarisme concentré.",
    actifs: "Tanins (10 %), acide ellagique, flavonoïdes, vitamine C (baies).",
    formes: "Infusion, gargarisme, cataplasme, sirop de baies.",
    posologie: "2 à 3 g par tasse, jusqu'à 3 fois par jour.",
    interactions: "Tanins : espacer de 2 h des médicaments.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Constipation possible en usage prolongé."
  },
  {
    id: "salsepareille-mex",
    nom: "Salsepareille du Mexique",
    latin: "Smilax aristolochiifolia",
    famille: "Smilacacées",
    image: null,
    emoji: "🌿",
    bienfaits: ["Drainage", "Peau", "Anti-inflammatoire", "Articulations"],
    parties: "Racine",
    usages: "Psoriasis, eczéma, acné, rhumatismes, drainage cutané.",
    preparation: "Décoction de racine 15 min, 2 tasses par jour.",
    actifs: "Saponines stéroïdennes (sarsasaponine), phytostérols.",
    formes: "Décoction, teinture-mère.",
    posologie: "1,5 à 3 g/j de racine en décoction, cures de 3 semaines.",
    interactions: "Prudence avec les digitaliques.",
    grossesse: "Déconseillée.",
    precaution: "Ne pas confondre avec les espèces d'Aristolochia (toxiques)."
  },
  {
    id: "sanguinaria",
    nom: "Sanguinaire du Canada",
    latin: "Sanguinaria canadensis",
    famille: "Papavéracées",
    image: null,
    emoji: "🌺",
    bienfaits: ["Antiseptique", "Toux", "Drainage"],
    parties: "Racine (homéopathie et usage professionnel uniquement)",
    usages: "Historique : catarrhes bronchiques, polypes nasaux (homéopathie).",
    preparation: "Homéopathie diluée uniquement.",
    actifs: "Alcaloïdes isoquinoléiques (sanguinarine : irritant et toxique).",
    formes: "Homéopathie diluée ; NE PAS utiliser la racine brute.",
    posologie: "Selon praticien.",
    interactions: "TOXIQUE à dose brute (cardiotoxicité, irritation sévère).",
    grossesse: "CONTRE-INDIQUÉE.",
    precaution: "⚠ TOXIQUE : usage professionnel encadré uniquement."
  },
  {
    id: "schisandra",
    nom: "Schisandra (baie aux 5 saveurs)",
    latin: "Schisandra chinensis",
    famille: "Schisandracées",
    image: null,
    emoji: "🔴",
    bienfaits: ["Foie", "Surrénales", "Mémoire", "Peau"],
    parties: "Baies",
    usages: "Protection hépatique, stress, concentration, peau, adaptogène majeur (TCM).",
    preparation: "Extrait standardisé en gélules, décoction de baies 20 min.",
    actifs: "Lignanes (schisandrine A, B, schizandrol), polyphénols.",
    formes: "Extrait standardisé (9 % schisandrine), baies séchées.",
    posologie: "500 mg à 2 g/j d'extrait standardisé, cures de 4 à 8 semaines.",
    interactions: "Prudence avec les médicaments hépatiques (induction CYP3A4).",
    grossesse: "CONTRE-INDIQUÉE (utérotonique).",
    precaution: "Reflux gastro-œsophagien : peut l'aggraver."
  },
  {
    id: "scutellaire",
    nom: "Scutellaire",
    latin: "Scutellaria lateriflora",
    famille: "Lamiacées",
    image: null,
    emoji: "💜",
    bienfaits: ["Anxiété", "Sommeil", "Nerfs", "Antispasmodique"],
    parties: "Parties aériennes",
    usages: "Anxiété, nervosité, insomnie, spasmophilie, sevrage de stimulants.",
    preparation: "Infusion 10 min, 1 à 2 tasses par jour, le soir.",
    actifs: "Baicaline, wogonine, flavonoïdes glycuronides.",
    formes: "Infusion, teinture-mère, gélules.",
    posologie: "1 à 2 g par tasse le soir, ou 30 gouttes de teinture.",
    interactions: "Potentialise les sédatifs.",
    grossesse: "Déconseillée (données insuffisantes).",
    precaution: "Rares cas d'hépatotoxicité signalés : cures courtes."
  },
  {
    id: "serpolet",
    nom: "Serpolet (thym sauvage)",
    latin: "Thymus serpyllum",
    famille: "Lamiacées",
    image: null,
    emoji: "🪻",
    bienfaits: ["Antiseptique", "Toux", "Digestion", "Décongestionnant"],
    parties: "Sommités fleuries",
    usages: "Bronchite, angine, digestion, antiseptique respiratoire et intestinal.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour en phase infectieuse.",
    actifs: "Huile essentielle (carvacrol, thymol, p-cymène), flavonoïdes.",
    formes: "Infusion, sirop, HE (avis professionnel).",
    posologie: "1 à 2 g par tasse, jusqu'à 3 fois par jour.",
    interactions: "Pas d'interaction majeure aux doses usuelles.",
    grossesse: "Infusion modérée OK ; HE à éviter.",
    precaution: "HE dermocaustique : toujours diluer."
  },
  {
    id: "soja",
    nom: "Soja (isoflavones)",
    latin: "Glycine max",
    famille: "Fabacées",
    image: null,
    emoji: "🫘",
    bienfaits: ["Bouffées de chaleur", "Cholestérol", "Cœur", "Peau"],
    parties: "Graines (isoflavones)",
    usages: "Ménopause (bouffées de chaleur), cholestérol, santé osseuse.",
    preparation: "Compléments d'isoflavones standardisés, alimentation (tofu, tempeh).",
    actifs: "Isoflavones (génistéine, daidzéine, glycitéine 40 %).",
    formes: "Gélules d'extrait standardisé, alimentation riche en soja fermenté.",
    posologie: "40 à 80 mg/j d'isoflavones, cures de 3 à 6 mois.",
    interactions: "MAJEUR : interfère avec le tamoxifène et la lévothyroxine (espacer 4 h).",
    grossesse: "Alimentaire OK ; extraits concentrés déconseillés.",
    precaution: "Cancer hormonodépendant : avis médical obligatoire ; prudence hypothyroïdie."
  },
  {
    id: "sorbus",
    nom: "Sorbier",
    latin: "Sorbus aucuparia",
    famille: "Rosacées",
    image: null,
    emoji: "🔴",
    bienfaits: ["Drainage", "Digestion", "Diurétique", "Circulation"],
    parties: "Écorce, Baies",
    usages: "Rétention d'eau, transit, drainage rénal, oligurie.",
    preparation: "Décoction d'écorce 15 min ; baies cuites en gelée.",
    actifs: "Tanins, acide parasorbique (baies crues toxiques), flavonoïdes.",
    formes: "Décoction, gelée de baies, teinture.",
    posologie: "1 à 2 g d'écorce par tasse, 2 fois par jour.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Déconseillée (baies).",
    precaution: "Baies crues toxiques : toujours cuites ; écorce séchée depuis 6 mois minimum."
  },
  {
    id: "spiralée",
    nom: "Spiruline",
    latin: "Arthrospira platensis",
    famille: "Phormidiacées",
    image: null,
    emoji: "🌀",
    bienfaits: ["Reminéralisant", "Immunité", "Tonique", "Antioxydant"],
    parties: "Cyanobactérie séchée",
    usages: "Fatigue, carences (fer, protéines), immunité, antioxydant, sportifs.",
    preparation: "Poudre en gélules, poudre à diluer dans un jus, cures de 3 semaines.",
    actifs: "Phycocyanine, protéines (60–70 %), fer, bêta-carotène, vitamine B12 analogue.",
    formes: "Poudre, gélules, comprimés.",
    posologie: "3 à 5 g par jour, cures de 3 semaines, à distance des repas (fer).",
    interactions: "Prudence avec les immunosuppresseurs et anticoagulants.",
    grossesse: "Autorisée si origine contrôlée (qualité microbiologique).",
    precaution: "Qualité cruciale : privilégier les lots testés (microcystines, métaux lourds)."
  },
  {
    id: "tilleul",
    nom: "Tilleul",
    latin: "Tilia cordata",
    famille: "Malvacées",
    image: null,
    emoji: "💛",
    bienfaits: ["Sommeil", "Nerfs", "Drainage", "Digestion"],
    parties: "Bractées et fleurs",
    usages: "Insomnie légère, nervosité des enfants, digestion, drainage digestif.",
    preparation: "Infusion 10 min à couvert, le soir, éventuellement avec du miel.",
    actifs: "Farnésol, tanins, mucilages, flavonoïdes (tiliroside).",
    formes: "Infusion, hydrolat, sirop.",
    posologie: "1,5 à 2 g par tasse, 2 à 3 tasses par jour ; enfant : 1 tasse légère le soir.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée.",
    precaution: "Très bien toléré, même chez l'enfant."
  },
  {
    id: "trèfle-rouge",
    nom: "Trèfle rouge",
    latin: "Trifolium pratense",
    famille: "Fabacées",
    image: null,
    emoji: "🍀",
    bienfaits: ["Bouffées de chaleur", "Peau", "Circulation", "Cholestérol"],
    parties: "Sommités fleuries",
    usages: "Ménopause, santé osseuse, peau, cholestérol (isoflavones).",
    preparation: "Infusion 10 min, 1 à 2 tasses par jour ; extraits standardisés.",
    actifs: "Isoflavones (formononétine, biochanine A, génistéine).",
    formes: "Infusion, extrait standardisé (Promensil 40 mg).",
    posologie: "40 à 80 mg/j d'isoflavones, cures de 3 à 6 mois.",
    interactions: "MAJEUR : anticoagulants, tamoxifène, contraceptifs hormonaux.",
    grossesse: "Déconseillé (isoflavones).",
    precaution: "Cancer hormonodépendant : éviter."
  },
  {
    id: "vetiver",
    nom: "Vétiver",
    latin: "Chrysopogon zizanioides",
    famille: "Poacées",
    image: null,
    emoji: "🌾",
    bienfaits: ["Nerfs", "Anxiété", "Circulation", "Peau"],
    parties: "Racines (huile essentielle)",
    usages: "Stress, ancrage émotionnel, circulation, soins cutanés.",
    preparation: "HE en diffusion douce, massage dilué.",
    actifs: "Vetivones, khusimol, vetiselinène.",
    formes: "HE en diffusion, massage dilué 10 %.",
    posologie: "Diffusion 30 min max ; massage 2 gouttes diluées.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée en diffusion modérée.",
    precaution: "Très bien tolérée."
  },
  {
    id: "vigne-blanc",
    nom: "Vigne blanche (sarments)",
    latin: "Vitis vinifera (sarments)",
    famille: "Vitacées",
    image: null,
    emoji: "🍇",
    bienfaits: ["Circulation", "Drainage", "Antioxydant", "Peau"],
    parties: "Sarments, Feuilles",
    usages: "Jambes lourdes, couperose, drainage, antioxydant capillaire.",
    preparation: "Décoction de sarments 15 min, en bain de pieds ou infusion de feuilles.",
    actifs: "Proanthocyanidines, flavonoïdes, tanins.",
    formes: "Décoction (bain de pieds), infusion de feuilles, macérat glycériné.",
    posologie: "Bain de pieds : 100 g de sarments en décoction pour 5 L d'eau chaude.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Usage externe très bien toléré."
  },
  {
    id: "yuzu",
    nom: "Yuzu",
    latin: "Citrus junos",
    famille: "Rutacées",
    image: null,
    emoji: "🍊",
    bienfaits: ["Drainage", "Immunité", "Nerfs", "Digestion"],
    parties: "Zeste, Jus",
    usages: "Drainage hépatique, stress, digestion, apaisement nerveux (aromathérapie).",
    preparation: "Jus en cuisine, HE du zeste en diffusion.",
    actifs: "Limonène, vitamine C, flavonoïdes hespéridine-like.",
    formes: "Jus, HE en diffusion, zeste en cuisine.",
    posologie: "Diffusion 30 min ; jus dilué en boisson.",
    interactions: "Pas d'interaction majeure connue (à différence du pamplemousse).",
    grossesse: "Autorisé.",
    precaution: "HE photosensibilisante sur la peau avant exposition solaire."
  }
];

export const ASSOCIATIONS_SUP2 = [
  {
    id: "confort-prostate",
    nom: "Confort prostatique",
    objectif: "Hypertrophie bénigne de la prostate et troubles urinaires",
    plantes: ["Épilobe", "Ortie", "Piloselle"],
    effet: "Réduit l'inconfort urinaire, draine et apaise l'inflammation prostatique.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de parties aériennes d'épilobe (1,5 g)",
      "1 c. à café de racine d'ortie (2 g)",
      "1 c. à café de parties aériennes de piloselle (1,5 g)",
      "400 ml d'eau"
    ],
    preparation: [
      "Placer les trois plantes dans l'eau frémissante.",
      "Infuser 10 minutes à couvert.",
      "Filtrer et boire réparti sur la journée, de préférence entre les repas."
    ],
    posologie: "2 à 3 tasses par jour en cure de 3 semaines, à renouveler après une semaine de pause.",
    conservation: "Mélange sec : 12 mois au sec et à l'abri de la lumière.",
    avertissement: "Toute affection prostatique nécessite un avis médical (dépistage)."
  },
  {
    id: "energie-intellectuelle",
    nom: "Énergie intellectuelle",
    objectif: "Fatigue mentale et concentration",
    plantes: ["Rhodiola", "Gingembre", "Basilic sacré (tulsi)"],
    effet: "Adaptogène combiné : redonne de la vigueur mentale et réduit le stress oxydatif cérébral.",
    temps: "5 min + 10 min d'infusion",
    ingredients: [
      "300 mg d'extrait de rhodiola standardisé (ou 1 c. à café de racine coupée)",
      "2 rondelles de gingembre frais",
      "1 c. à café de feuilles de basilic sacré (1 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Décocter le gingembre 5 minutes.",
      "Retirer du feu, ajouter rhodiola et basilic sacré.",
      "Infuser 10 minutes à couvert.",
      "Filtrer et boire le matin ou en début d'après-midi."
    ],
    posologie: "1 tasse le matin pendant 4 semaines, cures ponctuelles en période d'examens.",
    conservation: "Mélange sec : 12 mois. Infusion : dans la journée.",
    avertissement: "Éviter le soir (stimulant) ; prudence avec les antidépresseurs."
  },
  {
    id: "hormones-feminines",
    nom: "Équilibre féminin",
    objectif: "Syndrome prémenstruel et troubles hormonaux légers",
    plantes: ["Actée à grappes noires", "Trèfle rouge", "Millefeuille"],
    effet: "Module les récepteurs hormonaux, apaise les symptômes du cycle et les tensions mammaires.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "20 gouttes de teinture d'actée à grappes noires (hors infusion)",
      "1 c. à café de sommités fleuries de trèfle rouge (1 g)",
      "1 c. à café de sommités fleuries de millefeuille (1 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Infuser trèfle rouge et millefeuille 10 minutes.",
      "Filtrer et laisser tiédir.",
      "Ajouter la teinture d'actée hors du feu.",
      "Boire 1 à 2 fois par jour, surtout en phase prémenstruelle."
    ],
    posologie: "1 à 2 tasses par jour du 14e au 28e jour du cycle, en cure de 3 cycles.",
    conservation: "Mélange sec : 12 mois. Teinture : à l'abri de la lumière.",
    avertissement: "Contre-indiqué en cas d'antécédent de cancer hormonodépendant ; avis médical recommandé."
  },
  {
    id: "immunite-enfants",
    nom: "Immunité des enfants",
    objectif: "Prévention des infections hivernales chez l'enfant",
    plantes: ["Échinacée", "Sureau noir", "Tilleul"],
    effet: "Renforce les défenses naturelles en douceur, adapté aux enfants dès 3 ans.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1/2 c. à café de racine d'échinacée (1 g)",
      "1 c. à café de baies de sureau noir (2 g)",
      "1 c. à café de fleurs de tilleul (1,5 g)",
      "300 ml d'eau",
      "1 c. à café de miel (dès 1 an)"
    ],
    preparation: [
      "Décocter l'échinacée 5 minutes.",
      "Retirer du feu, ajouter sureau et tilleul.",
      "Infuser 10 minutes.",
      "Filtrer, sucrer au miel une fois tiède."
    ],
    posologie: "1 tasse par jour pendant les périodes à risque, à partir de 3 ans.",
    conservation: "Mélange sec : 12 mois. Préparation : dans la journée.",
    avertissement: "Échinacée : cures courtes chez l'enfant (10 jours max). Miel interdit avant 1 an."
  },
  {
    id: "insomnie-profonde",
    nom: "Insomnie profonde",
    objectif: "Insomnie d'endormissement résistante",
    plantes: ["Valériane", "Passiflore", "Houblon", "Scutellaire"],
    effet: "Sédation naturelle par 4 plantes synergiques, facilite l'endormissement sans accoutumance.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de racine de valériane (2 g)",
      "1 c. à café de parties aériennes de passiflore (1,5 g)",
      "1 c. à café de cônes de houblon (1 g)",
      "1/2 c. à café de parties aériennes de scutellaire (0,75 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Décocter la valériane 5 minutes (racine).",
      "Retirer du feu, ajouter passiflore, houblon et scutellaire.",
      "Infuser 10 minutes à couvert (retenir les composés volatils).",
      "Filtrer et boire lentement 30 minutes avant le coucher."
    ],
    posologie: "1 tasse le soir, cures de 3 semaines maximum.",
    conservation: "Mélange sec : 12 mois dans un bocal hermétique.",
    avertissement: "Somnolence : ne pas conduire ; prudence avec les sédatifs médicamenteux."
  },
  {
    id: "jambes-lourdes-grossesse",
    nom: "Jambes légères (grossesse)",
    objectif: "Insuffisance veineuse pendant la grossesse",
    plantes: ["Mélisse", "Mauve", "Tilleul"],
    effet: "Confort veineux doux, sans plantes contre-indiquées pendant la grossesse.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de feuilles de mélisse (1,5 g)",
      "1 c. à soupe de fleurs de mauve (2 g)",
      "1 c. à café de fleurs de tilleul (1,5 g)",
      "350 ml d'eau"
    ],
    preparation: [
      "Chauffer l'eau à 90 °C.",
      "Verser sur le mélange et couvrir.",
      "Infuser 10 minutes.",
      "Filtrer et boire tiède, 1 à 2 fois par jour."
    ],
    posologie: "1 à 2 tasses par jour, associé à des douches froides sur les jambes.",
    conservation: "Mélange sec : 12 mois.",
    avertissement: "Vigne rouge et cyprès contre-indiqués en grossesse : ce trio est sûr."
  },
  {
    id: "lactation-boost",
    nom: "Lactation soutenue",
    objectif: "Stimulation de la production de lait",
    plantes: ["Fenugrec", "Fenouil", "Houblon"],
    effet: "Galactogènes combinés : stimule la lactation et apaise les coliques du nourrisson.",
    temps: "5 min + 15 min de décoction",
    ingredients: [
      "1 c. à café de graines de fenugrec (2 g)",
      "1 c. à café de graines de fenouil écrasées (2 g)",
      "1/2 c. à café de cônes de houblon (0,75 g)",
      "350 ml d'eau"
    ],
    preparation: [
      "Décocter le fenugrec 15 minutes à couvert.",
      "Retirer du feu, ajouter fenouil écrasé et houblon.",
      "Infuser 10 minutes.",
      "Filtrer et boire tiède, 2 fois par jour."
    ],
    posologie: "2 tasses par jour jusqu'à stabilisation de la lactation.",
    conservation: "Mélange sec : 12 mois.",
    avertissement: "Fenugrec : prudence si diabète ou hypothyroïdie traitée."
  },
  {
    id: "microbiote-bilan",
    nom: "Microbiote apaisé",
    objectif: "Colopathie fonctionnelle et transit irritable",
    plantes: ["Menthe poivrée", "Camomille matricaire", "Mélisse", "Aneth"],
    effet: "Antispasmodique digestif global, apaise ballonnements et douleurs du côlon.",
    temps: "3 min + 8 min d'infusion",
    ingredients: [
      "1/2 c. à café de feuilles de menthe poivrée (0,75 g)",
      "1/2 c. à café de fleurs de camomille (0,75 g)",
      "1/2 c. à café de feuilles de mélisse (0,75 g)",
      "1/2 c. à café de graines d'aneth écrasées (0,75 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Chauffer l'eau à 90 °C.",
      "Verser sur le mélange et couvrir.",
      "Infuser 8 minutes.",
      "Filtrer et boire après les repas."
    ],
    posologie: "1 à 2 tasses après les repas, en cure de 3 semaines.",
    conservation: "Mélange sec : 12 mois.",
    avertissement: "Menthe : éviter en cas de reflux gastro-œsophagien."
  },
  {
    id: "migration-sereine",
    nom: "Migraine apaisée",
    objectif: "Migraine et céphalées de tension récurrentes",
    plantes: ["Menthe poivrée", "Pétasite", "Lavande vraie"],
    effet: "Réduit la fréquence des migraines (pétasite), soulage à la crise (menthe, lavande).",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "50 à 75 mg d'extrait de pétasite standardisé (sans PA), en gélule",
      "1 goutte d'HE de menthe poivrée (sur les tempes, diluée)",
      "2 gouttes d'HE de lavande vraie (en massage des tempes)",
      "1 tasse d'infusion de camomille (adjuvant calmant)"
    ],
    preparation: [
      "En prévention : gélule de pétasite le matin pendant 3 mois.",
      "À la crise : masser les tempes avec les HE diluées dans 1 c. à café d'huile végétale.",
      "Boire lentement une tasse d'infusion de camomille.",
      "Se reposer dans une pièce sombre et calme."
    ],
    posologie: "Prévention : 1 gélule/jour 3 mois. Crise : application locale au besoin.",
    conservation: "HE à l'abri de la lumière.",
    avertissement: "Pétasite : UNIQUEMENT extraits certifiés sans alcaloïdes PA ; interdit pendant la grossesse."
  },
  {
    id: "minceur-douce",
    nom: "Minceur douce",
    objectif: "Accompagnement naturel de la perte de poids",
    plantes: ["Fucus (algue brune)", "Pissenlit", "Éleuthérocoque"],
    effet: "Satietogène (fucus), drainage (pissenlit) et stimulation métabolique douce (maté).",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de thalle de fucus en poudre (1 g)",
      "1 c. à café de racine de pissenlit (2 g)",
      "1 c. à café de feuilles de maté (2 g)",
      "400 ml d'eau"
    ],
    preparation: [
      "Infuser pissenlit et maté 10 minutes.",
      "Ajouter la poudre de fucus hors du feu et remuer.",
      "Boire réparti sur la matinée."
    ],
    posologie: "1 préparation par jour en cure de 3 semaines, en complément d'un régime équilibré.",
    conservation: "Mélange sec : 12 mois. Préparation : dans la journée.",
    avertissement: "Fucus contre-indiqué en cas de thyropathie ; maté : éviter le soir."
  },
  {
    id: "membrane-neurones",
    nom: "Mémoire long terme",
    objectif: "Soutien cognitif et prévention du déclin",
    plantes: ["Ginkgo biloba", "Schisandra (baie aux 5 saveurs)", "Curcuma"],
    effet: "Améliore la microcirculation cérébrale, protège les neurones du stress oxydatif.",
    temps: "5 min + 15 min de décoction",
    ingredients: [
      "120 mg d'extrait de ginkgo standardisé (gélule)",
      "500 mg d'extrait de schisandra standardisé (gélule)",
      "1/2 c. à café de curcuma en poudre (1 g)",
      "1 pincée de poivre noir",
      "200 ml de lait végétal chaud"
    ],
    preparation: [
      "Chauffer le lait végétal sans bouillir.",
      "Ajouter curcuma et poivre noir, remuer.",
      "Prendre les 2 gélules avec la boisson tiède.",
      "Boire le matin, en cure de 2 à 3 mois."
    ],
    posologie: "1 préparation par jour en cure de 2 à 3 mois.",
    conservation: "Poudres et gélules au sec.",
    avertissement: "Ginkgo : arrêt 4 jours avant chirurgie ; prudence sous anticoagulants."
  },
  {
    id: "os-solides",
    nom: "Ossature solide",
    objectif: "Prévention de l'ostéoporose et reminéralisation",
    plantes: ["Bambou (tabashir)", "Ortie", "Spiruline"],
    effet: "Silice organique et minéraux biodisponibles : soutient la densité osseuse.",
    temps: "4 h de macération à froid",
    ingredients: [
      "300 mg de silice de bambou (gélule)",
      "1 c. à soupe de feuilles d'ortie (3 g)",
      "1 c. à soupe de feuilles d'alfalfa (3 g)",
      "500 ml d'eau"
    ],
    preparation: [
      "Placer ortie et alfalfa dans l'eau froide.",
      "Laisser macérer 4 heures (minéraux mieux extraits).",
      "Filtrer, réchauffer doucement si souhaité.",
      "Prendre la gélule de silice avec la préparation."
    ],
    posologie: "1 préparation par jour en cure de 3 mois, renouvelable.",
    conservation: "Préparation : 24 h au frais.",
    avertissement: "Prudence sous diurétiques ; alfalfa : contre-indiqué en maladie auto-immune."
  },
  {
    id: "peau-eczema",
    nom: "Peau apaisée (eczéma)",
    objectif: "Eczéma sec et peau atopique",
    plantes: ["Bourrache", "Chanvre (graines)", "Camomille matricaire"],
    effet: "AGL et oméga-3 pour la barrière cutanée, camomille anti-inflammatoire en interne.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 g d'huile de bourrache (gélule)",
      "1 c. à café d'huile de chanvre (alimentaire, assaisonnement)",
      "1 c. à soupe de fleurs de camomille matricaire (3 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Infuser la camomille 10 minutes, filtrer, boire tiède.",
      "Prendre la gélule d'huile de bourrache au cours du repas.",
      "Ajouter l'huile de chanvre en assaisonnement d'un plat (jamais chauffée)."
    ],
    posologie: "En cure de 2 à 3 mois, complétée par une crème de bourrache en usage externe.",
    conservation: "Huiles au frais à l'abri de la lumière.",
    avertissement: "Usage alimentaire d'huiles vierges premières pressions uniquement."
  },
  {
    id: "tonus-matin",
    nom: "Tonus du matin",
    objectif: "Asthénie matinale et réveil difficile",
    plantes: ["Ginseng", "Gentiane jaune", "Citron"],
    effet: "Stimulant physique (ginseng), digestif amer (gentiane) et drainant (citron).",
    temps: "5 min + 10 min de macération",
    ingredients: [
      "200 mg d'extrait de ginseng rouge standardisé (gélule)",
      "20 gouttes de teinture de gentiane",
      "1/2 citron pressé",
      "200 ml d'eau tiède"
    ],
    preparation: [
      "Presser le demi-citron dans l'eau tiède.",
      "Ajouter la teinture de gentiane.",
      "Prendre la gélule de ginseng avec la préparation.",
      "Boire à jeun, 20 minutes avant le petit-déjeuner."
    ],
    posologie: "1 préparation chaque matin pendant 3 semaines, puis 1 semaine de pause.",
    conservation: "Préparation immédiate.",
    avertissement: "Gentiane : hypertension non contrôlée et gastrite aiguë : éviter."
  }
];
