// Données de L'Herbier Médicinal — contenu extrait et enrichi (usage éducatif).
// Chaque plante : nom, latin, famille, image, bienfaits (tags), parties, usages,
// préparation + champs phytothérapeutiques (actifs, formes, posologie,
// interactions, grossesse). Chaque association : objectif, plantes, recette complète.

export const PLANTES = [
  {
    id: "aubepine",
    nom: "Aubépine",
    latin: "Crataegus monogyna",
    famille: "Rosacées",
    image: "images/aubepine.jpg",
    bienfaits: ["Cœur", "Anxiété", "Tension artérielle", "Sommeil"],
    parties: "Fleurs, Feuilles",
    usages: "Palpitations, nervosité cardiaque, hypertension légère.",
    preparation: "Infusion 10 min, 2 tasses par jour, en cure de 3 semaines.",
    actifs: "Flavonoïdes (vitexine, hyperoside), procyanidines, triterpènes.",
    formes: "Infusion, extrait sec standardisé, teinture-mère, macérat glycériné.",
    posologie: "2 tasses par jour (1,5 g/tasse), ou 160–900 mg/j d'extrait standardisé en flavonoïdes.",
    interactions: "Potentialise les antihypertenseurs et digitaliques : avis médical.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Avis médical requis en cas de traitement cardiaque."
  },
  {
    id: "camomille-matricaire",
    nom: "Camomille matricaire",
    latin: "Matricaria recutita",
    famille: "Astéracées",
    image: "images/camomille-matricaire.jpg",
    bienfaits: ["Digestion", "Sommeil", "Anti-inflammatoire", "Apaisant"],
    parties: "Fleurs",
    usages: "Troubles digestifs, nervosité, irritations de la peau et des yeux.",
    preparation: "Infusion : 1 c. à soupe de fleurs pour 250 ml d'eau frémissante, 5 à 10 min.",
    actifs: "Apigénine, α-bisabolol, chamazulène, matricine.",
    formes: "Infusion, HE, hydrolat, macérat huileux, cataplasme.",
    posologie: "1 à 3 tasses par jour ; en compresses : infusion refroidie sur les yeux.",
    interactions: "Potentialise la warfarine et les sédatifs à forte dose.",
    grossesse: "Infusion modérée autorisée.",
    precaution: "Éviter en cas d'allergie aux Astéracées."
  },
  {
    id: "cassis",
    nom: "Cassis",
    latin: "Ribes nigrum",
    famille: "Grossulariacées",
    image: "images/cassis.jpg",
    bienfaits: ["Articulations", "Anti-inflammatoire", "Allergies", "Drainage"],
    parties: "Feuilles, Baies",
    usages: "Arthrose, rhumatismes, allergies saisonnières.",
    preparation: "Infusion de feuilles 10 min, 2 à 3 tasses par jour.",
    actifs: "Flavonoïdes (rutine, hyperoside), prodelphinidines, vitamine C (baies).",
    formes: "Infusion, macérat glycériné de bourgeons, extrait sec.",
    posologie: "2 à 3 tasses par jour ; bourgeons : 5 à 15 gouttes 2 fois par jour.",
    interactions: "Potentialise les anticoagulants et antihypertenseurs.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Prudence en cas de traitement anticoagulant."
  },
  {
    id: "curcuma",
    nom: "Curcuma",
    latin: "Curcuma longa",
    famille: "Zingibéracées",
    image: "images/curcuma.jpg",
    bienfaits: ["Anti-inflammatoire", "Antioxydant", "Foie", "Articulations"],
    parties: "Rhizome",
    usages: "Douleurs articulaires chroniques, digestion, soutien hépatique.",
    preparation: "Poudre associée à du poivre noir et un corps gras.",
    actifs: "Curcuminoïdes (curcumine 3–5 %), huile essentielle (turmerone).",
    formes: "Poudre, extrait sec standardisé (95 % curcuminoïdes), HE.",
    posologie: "500 mg à 2 g/j de poudre ; extrait : 200–400 mg/j, avec poivre et corps gras.",
    interactions: "Anticoagulants, antidiabétiques : prudence ; réduit l'absorption du fer.",
    grossesse: "Doses alimentaires OK ; extraits concentrés déconseillés.",
    precaution: "Déconseillé en cas d'obstruction des voies biliaires."
  },
  {
    id: "echinacee",
    nom: "Échinacée",
    latin: "Echinacea purpurea",
    famille: "Astéracées",
    image: "images/echinacee.jpg",
    bienfaits: ["Immunité", "Antiviral", "Infections ORL"],
    parties: "Racine, Parties aériennes",
    usages: "Prévention et début de rhume, infections hivernales récurrentes.",
    preparation: "Teinture-mère ou décoction, en cures courtes de 10 jours.",
    actifs: "Polysaccharides, alkylamides, acide chicorique (E. purpurea).",
    formes: "Teinture-mère, extrait sec, jus frais de plante pressée.",
    posologie: "Dès les premiers signes : 40–60 gouttes de teinture 3 fois par jour, 5 à 10 jours.",
    interactions: "Immunosuppresseurs : contre-indiquée.",
    grossesse: "Cures courtes possibles sous avis.",
    precaution: "À éviter en cas de maladie auto-immune."
  },
  {
    id: "fenouil",
    nom: "Fenouil",
    latin: "Foeniculum vulgare",
    famille: "Apiacées",
    image: "images/fenouil.jpg",
    bienfaits: ["Digestion", "Ballonnements", "Lactation", "Toux"],
    parties: "Graines",
    usages: "Ballonnements, coliques, digestion difficile.",
    preparation: "Infusion de graines écrasées, 10 min.",
    actifs: "Huile essentielle (trans-anéthole 50–70 %, fenchone), flavonoïdes.",
    formes: "Infusion, HE, hydrolat, graines à mâcher.",
    posologie: "1 à 3 tasses par jour (1,5–2,5 g de graines écrasées/tasse).",
    interactions: "Pas d'interaction majeure aux doses usuelles.",
    grossesse: "Doses culinaires OK ; HE déconseillée.",
    precaution: "Éviter les doses élevées pendant la grossesse."
  },
  {
    id: "gingembre",
    nom: "Gingembre",
    latin: "Zingiber officinale",
    famille: "Zingibéracées",
    image: "images/gingembre.jpg",
    bienfaits: ["Nausées", "Anti-inflammatoire", "Circulation", "Immunité"],
    parties: "Rhizome",
    usages: "Mal des transports, nausées, douleurs articulaires, refroidissements.",
    preparation: "Décoction de rhizome frais 10 min, avec citron et miel.",
    actifs: "Gingérols, shogaols, zingibérène.",
    formes: "Rhizome frais, poudre en gélules, sirop, confit.",
    posologie: "Nausées : 1 à 2 g de rhizome frais par jour ; décoction : 2 g dans 250 ml.",
    interactions: "Anticoagulants, antidiabétiques, antihypertenseurs : prudence.",
    grossesse: "Nausées de grossesse : 1 g/j maximum, cures courtes.",
    precaution: "Prudence sous anticoagulants et en cas de calculs biliaires."
  },
  {
    id: "lavande-vraie",
    nom: "Lavande vraie",
    latin: "Lavandula angustifolia",
    famille: "Lamiacées",
    image: "images/lavande-vraie.jpg",
    bienfaits: ["Sommeil", "Anxiété", "Antispasmodique", "Cicatrisant"],
    parties: "Fleurs",
    usages: "Stress, insomnie, tensions nerveuses, petites brûlures.",
    preparation: "Infusion de fleurs ou huile essentielle diluée en massage.",
    actifs: "Linalol, acétate de linalyle, coumarines (ombelliférone).",
    formes: "Infusion, HE, hydrolat, sachets, extrait standardisé (Silexan 80 mg).",
    posologie: "1 tasse le soir (1,5 g de fleurs) ; HE : 2 gouttes sur sucre ou en massage diluée 5 %.",
    interactions: "Potentialise les sédatifs et anxiolytiques.",
    grossesse: "Infusion OK ; HE interdite chez le nourrisson et par voie orale enceinte.",
    precaution: "Huile essentielle interdite chez le nourrisson et la femme enceinte."
  },
  {
    id: "melisse",
    nom: "Mélisse",
    latin: "Melissa officinalis",
    famille: "Lamiacées",
    image: "images/melisse.jpg",
    bienfaits: ["Sommeil", "Anxiété", "Digestion", "Antiviral"],
    parties: "Feuilles",
    usages: "Nervosité, digestion difficile d'origine nerveuse, herpès labial.",
    preparation: "Infusion 10 min, 2 à 3 tasses par jour.",
    actifs: "Huile essentielle (citral, géraniol), acide rosmarinique, flavonoïdes.",
    formes: "Infusion, teinture, macérat huileux (herpès), gélules d'extrait.",
    posologie: "2 à 3 tasses par jour ; herpès : macérat huileux en application 3 fois par jour.",
    interactions: "Potentialise les sédatifs et thyroïdiens (surveillance TSH).",
    grossesse: "Autorisée en infusion modérée.",
    precaution: "Prudence en cas d'hypothyroïdie."
  },
  {
    id: "menthe-poivree",
    nom: "Menthe poivrée",
    latin: "Mentha × piperita",
    famille: "Lamiacées",
    image: "images/menthe-poivree.jpg",
    bienfaits: ["Digestion", "Maux de tête", "Nausées", "Décongestionnant"],
    parties: "Feuilles",
    usages: "Ballonnements, spasmes digestifs, migraines, rhume.",
    preparation: "Infusion de feuilles fraîches ou séchées, 5 min.",
    actifs: "Menthol (30–55 %), menthone, flavonoïdes.",
    formes: "Infusion, HE, gélules gastrorésistantes (SII), roll-on (tempes).",
    posologie: "Infusion : 1 à 3 tasses par jour ; HE : 1 goutte sur sucre ou 2 gouttes diluées sur les tempes.",
    interactions: "Peut réduire l'absorption du fer ; prudence avec les AINS.",
    grossesse: "Infusion modérée OK ; HE déconseillée allaitement (baisse de lait).",
    precaution: "Déconseillée aux enfants de moins de 7 ans et en cas de reflux."
  },
  {
    id: "millepertuis",
    nom: "Millepertuis",
    latin: "Hypericum perforatum",
    famille: "Hypéricacées",
    image: "images/millepertuis.jpg",
    bienfaits: ["Humeur", "Sommeil", "Cicatrisant", "Nerfs"],
    parties: "Sommités fleuries",
    usages: "Déprime légère à modérée, brûlures (en huile).",
    preparation: "Infusion ou macérat huileux pour usage externe.",
    actifs: "Hyperforine, hypéricine, flavonoïdes (quercétine).",
    formes: "Extrait sec standardisé, infusion, macérat huileux (brûlures).",
    posologie: "Déprime légère : 300 à 900 mg/j d'extrait standardisé (0,3 % hypéricine), cure de 4 à 6 semaines.",
    interactions: "MAJEUR : pilule contraceptive, antidépresseurs (IMAO, ISRS), anticoagulants, immunosuppresseurs.",
    grossesse: "Déconseillé.",
    precaution: "Nombreuses interactions médicamenteuses (pilule, antidépresseurs) et photosensibilisant."
  },
  {
    id: "ortie",
    nom: "Ortie",
    latin: "Urtica dioica",
    famille: "Urticacées",
    image: "images/ortie.jpg",
    bienfaits: ["Reminéralisant", "Anti-inflammatoire", "Diurétique", "Cheveux et ongles"],
    parties: "Feuilles, Racine",
    usages: "Fatigue, carences en fer, rhumatismes, troubles urinaires.",
    preparation: "Infusion longue (4 h à froid) ou en soupe.",
    actifs: "Minéraux (fer, silice, potassium), acide formique (frais), β-sitostérol (racine).",
    formes: "Infusion, poudre en gélules, jus frais, soupe, cataplasme.",
    posologie: "2 à 3 tasses par jour (infusion froide de 1,5 g) ; rhumatismes : 600 mg/j d'extrait sec.",
    interactions: "Diurétiques, antihypertenseurs : prudence.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Prudence avec les traitements diurétiques."
  },
  {
    id: "passiflore",
    nom: "Passiflore",
    latin: "Passiflora incarnata",
    famille: "Passifloracées",
    image: "images/passiflore.jpg",
    bienfaits: ["Anxiété", "Sommeil", "Antispasmodique"],
    parties: "Parties aériennes",
    usages: "Anxiété, réveils nocturnes, palpitations nerveuses.",
    preparation: "Infusion 10 min en fin de journée.",
    actifs: "Flavonoïdes (vitexine, isovitexine), harmane alcaloïdes traces.",
    formes: "Infusion, teinture-mère, gélules, association avec valériane.",
    posologie: "1 à 2 g par tasse, 2 à 3 fois par jour dont une le soir.",
    interactions: "Potentialise les sédatifs et anticoagulants à forte dose.",
    grossesse: "Autorisée en infusion modérée.",
    precaution: "Somnolence possible ; prudence avec les sédatifs."
  },
  {
    id: "plantain-lanceole",
    nom: "Plantain lancéolé",
    latin: "Plantago lanceolata",
    famille: "Plantaginacées",
    image: "images/plantain-lanceole.jpg",
    bienfaits: ["Allergies", "Toux", "Cicatrisant", "Antiseptique"],
    parties: "Feuilles",
    usages: "Rhinite allergique, toux irritative, piqûres d'insectes.",
    preparation: "Infusion 10 min ou feuille froissée en application locale.",
    actifs: "Mucilages, aucubine (glucoside iridoïde), flavonoïdes, tanins.",
    formes: "Infusion, sirop (toux), cataplasme de feuilles fraîches, macérat huileux.",
    posologie: "2 à 3 tasses par jour ; piqûres : feuille froissée en friction immédiate.",
    interactions: "Aucune connue aux doses usuelles.",
    grossesse: "Autorisé.",
    precaution: "Très bien toléré."
  },
  {
    id: "reglisse",
    nom: "Réglisse",
    latin: "Glycyrrhiza glabra",
    famille: "Fabacées",
    image: "images/reglisse.jpg",
    bienfaits: ["Estomac", "Toux", "Anti-inflammatoire", "Surrénales"],
    parties: "Racine",
    usages: "Brûlures d'estomac, toux sèche, fatigue chronique.",
    preparation: "Décoction de racine 10 min.",
    actifs: "Glycyrrhizine (5–10 %), flavonoïdes (glabridine), polysaccharides.",
    formes: "Décoction, bâton à mâcher, teinture, DGL (déglycyrrhizinée).",
    posologie: "Estomac : 1 tasse après les repas, 3 semaines maximum ; DGL sans limite d'hypertension.",
    interactions: "Diurétiques thiazidiques, digitaliques, corticoïdes : risque d'hypokaliémie.",
    grossesse: "Déconseillée à doses thérapeutiques (risque d'œdème).",
    precaution: "Contre-indiquée en cas d'hypertension ; pas plus de 3 semaines."
  },
  {
    id: "romarin",
    nom: "Romarin",
    latin: "Rosmarinus officinalis",
    famille: "Lamiacées",
    image: "images/romarin.jpg",
    bienfaits: ["Foie", "Mémoire", "Tonique", "Digestion"],
    parties: "Feuilles, Sommités",
    usages: "Digestion lente, fatigue intellectuelle, drainage hépatique.",
    preparation: "Infusion 10 min le matin et le midi.",
    actifs: "Acide rosmarinique, camphre, cinéole, diterpènes (carnosol).",
    formes: "Infusion, HE, extrait sec, vin médical.",
    posologie: "2 tasses par jour le matin et le midi (1,5 g/tasse) ; HE : avis professionnel.",
    interactions: "HE : prudence épilepsie et hypertension non contrôlée.",
    grossesse: "Infusion OK ; HE déconseillée.",
    precaution: "Éviter le soir et en cas d'hypertension non contrôlée."
  },
  {
    id: "sauge-officinale",
    nom: "Sauge officinale",
    latin: "Salvia officinalis",
    famille: "Lamiacées",
    image: "images/sauge-officinale.jpg",
    bienfaits: ["Bouffées de chaleur", "Transpiration", "Maux de gorge", "Digestion"],
    parties: "Feuilles",
    usages: "Ménopause, sudation excessive, angines.",
    preparation: "Infusion 10 min, en gargarisme ou en boisson.",
    actifs: "Huile essentielle (thuyone, camphre), acide rosmarinique, tanins.",
    formes: "Infusion, gargarisme, teinture, gélules d'extrait (sudation).",
    posologie: "Sudation : 2 à 3 tasses par jour ; gargarisme : infusion concentrée tiède 3 fois par jour.",
    interactions: "Prudence avec les antioestrogènes (effet hormonal léger).",
    grossesse: "CONTRE-INDIQUÉE (thuyone, effet éménagogue).",
    precaution: "Contre-indiquée pendant la grossesse, l'allaitement et en cas de cancer hormonodépendant."
  },
  {
    id: "sureau-noir",
    nom: "Sureau noir",
    latin: "Sambucus nigra",
    famille: "Adoxacées",
    image: "images/sureau-noir.jpg",
    bienfaits: ["Fièvre", "Immunité", "Antiviral", "Sudorifique"],
    parties: "Fleurs, Baies",
    usages: "États grippaux, rhume, fièvre.",
    preparation: "Infusion de fleurs ou sirop de baies cuites.",
    actifs: "Anthocyanes (baies), flavonoïdes, acides chlorogéniques (flevers).",
    formes: "Sirop de baies cuites, infusion de fleurs, extrait standardisé (Sambucol).",
    posologie: "Grippe : 15 ml de sirop 3 fois par jour dès les premiers signes, 5 jours.",
    interactions: "Immunosuppresseurs : prudence ; diabète : surveiller la glycémie (sirop).",
    grossesse: "Sirop de baies cuites : doses usuelles OK.",
    precaution: "Baies crues toxiques : toujours les cuire."
  },
  {
    id: "thym",
    nom: "Thym",
    latin: "Thymus vulgaris",
    famille: "Lamiacées",
    image: "images/thym.jpg",
    bienfaits: ["Antiseptique", "Toux", "Immunité", "Digestion"],
    parties: "Sommités fleuries, Feuilles",
    usages: "Infections respiratoires, maux de gorge, toux grasse.",
    preparation: "Infusion 10 min, en gargarisme ou en boisson chaude avec du miel.",
    actifs: "Thymol, carvacrol, flavonoïdes, acide rosmarinique.",
    formes: "Infusion, sirop, HE (chimiotypes thujanol/linalol), sirop pour toux.",
    posologie: "3 tasses par jour en phase infectieuse (1,5 g/tasse) ; gargarisme concentré 3 fois par jour.",
    interactions: "Pas d'interaction majeure aux doses usuelles.",
    grossesse: "Infusion modérée OK ; HE à éviter.",
    precaution: "Éviter à fortes doses chez la femme enceinte."
  },
  {
    id: "valeriane",
    nom: "Valériane",
    latin: "Valeriana officinalis",
    famille: "Caprifoliacées",
    image: "images/valeriane.jpg",
    bienfaits: ["Sommeil", "Anxiété", "Relaxant musculaire"],
    parties: "Racine",
    usages: "Insomnie d'endormissement, agitation nerveuse.",
    preparation: "Décoction ou teinture, le soir.",
    actifs: "Acide valérénique, valepotriates, GABA et glutamine.",
    formes: "Décoction, teinture, gélules d'extrait sec, association passiflore.",
    posologie: "Sommeil : 300 à 600 mg d'extrait sec 30 minutes avant le coucher.",
    interactions: "Potentialise les somnifères, anxiolytiques et alcool.",
    grossesse: "Déconseillée (données insuffisantes).",
    precaution: "Peut potentialiser les somnifères ; pas de conduite après prise."
  }
];

export const ASSOCIATIONS = [
  {
    id: "anti-allergie-de-saison",
    nom: "Anti-allergie de saison",
    objectif: "Rhinite allergique",
    plantes: ["Plantain lancéolé", "Cassis", "Ortie"],
    effet: "Réduit la réaction inflammatoire des muqueuses au printemps.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de plantain lancéolé (1,5 g)",
      "1 c. à café de feuilles de cassis (1,5 g)",
      "1 c. à café de feuilles d'ortie (1,5 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Mélanger les trois plantes à parts égales.",
      "Verser l'eau à 90 °C sur le mélange.",
      "Couvrir et infuser 10 minutes.",
      "Filtrer finement.",
      "Boire réparti sur la journée."
    ],
    posologie: "3 tasses par jour, à débuter 3 semaines avant la saison pollinique.",
    conservation: "Mélange sec : 12 mois au sec et à l'abri de la lumière.",
    avertissement: "Ne remplace pas un traitement antiallergique prescrit."
  },
  {
    id: "bouclier-hivernal",
    nom: "Bouclier hivernal",
    objectif: "Rhume et états grippaux",
    plantes: ["Sureau noir", "Échinacée", "Thym", "Gingembre"],
    effet: "Stimule les défenses, fait transpirer et assainit les voies respiratoires.",
    temps: "5 min + 20 min de cuisson/infusion",
    ingredients: [
      "2 g de gingembre frais râpé (≈ 3 rondelles)",
      "1 c. à café de baies de sureau noir séchées (2 g)",
      "1 c. à café de racine d'échinacée (2 g)",
      "1 c. à café de thym séché (1 g)",
      "350 ml d'eau",
      "miel de thym à volonté"
    ],
    preparation: [
      "Mettre le gingembre et l'échinacée dans l'eau froide.",
      "Porter à ébullition puis laisser en décoction 10 minutes à couvert.",
      "Retirer du feu, ajouter le sureau et le thym.",
      "Couvrir et laisser infuser 10 minutes hors du feu.",
      "Filtrer et ajouter le miel une fois la boisson tiédie."
    ],
    posologie: "3 tasses par jour dès les premiers signes, pendant 5 à 7 jours.",
    conservation: "Préparation : 24 h au réfrigérateur, à réchauffer doucement.",
    avertissement: "Échinacée déconseillée en cas de maladie auto-immune."
  },
  {
    id: "calme-interieur",
    nom: "Calme intérieur",
    objectif: "Stress et anxiété diurne",
    plantes: ["Mélisse", "Aubépine", "Passiflore"],
    effet: "Apaise le système nerveux sans somnolence marquée, régule les palpitations.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de feuilles de mélisse (1,5 g)",
      "1 c. à café de sommités fleuries d'aubépine (1,5 g)",
      "1 c. à café de passiflore (1,5 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Mélanger les trois plantes à parts égales.",
      "Chauffer l'eau à 90 °C.",
      "Verser sur les plantes et couvrir immédiatement.",
      "Infuser 10 minutes.",
      "Filtrer et boire sans sucre de préférence."
    ],
    posologie: "2 à 3 tasses réparties dans la journée, dont une en fin d'après-midi.",
    conservation: "Mélange sec : 12 mois. Infusion : dans la journée.",
    avertissement: "Avis médical si traitement cardiaque ou anxiolytique."
  },
  {
    id: "confort-articulaire",
    nom: "Confort articulaire",
    objectif: "Douleurs articulaires et arthrose",
    plantes: ["Curcuma", "Cassis", "Gingembre", "Ortie"],
    effet: "Combinaison anti-inflammatoire et reminéralisante, en cure de fond.",
    temps: "5 min + 20 min",
    ingredients: [
      "1 c. à café de curcuma en poudre ou râpé (2 g)",
      "2 g de gingembre frais râpé",
      "1 c. à café de feuilles de cassis (1,5 g)",
      "1 c. à café de feuilles d'ortie (1,5 g)",
      "400 ml d'eau",
      "1 pincée de poivre noir",
      "1 c. à café d'huile d'olive (facultatif)"
    ],
    preparation: [
      "Mettre curcuma et gingembre dans l'eau froide avec le poivre.",
      "Porter à ébullition et maintenir la décoction 10 minutes.",
      "Retirer du feu et ajouter cassis et ortie.",
      "Couvrir et infuser 10 minutes.",
      "Filtrer ; ajouter l'huile d'olive pour améliorer l'absorption de la curcumine."
    ],
    posologie: "2 tasses par jour pendant 3 semaines, puis 1 semaine de pause.",
    conservation: "Préparation : 24 h au frais.",
    avertissement: "Prudence sous anticoagulants."
  },
  {
    id: "detox-du-foie",
    nom: "Détox du foie",
    objectif: "Digestion lourde, soutien hépatique",
    plantes: ["Romarin", "Curcuma", "Menthe poivrée"],
    effet: "Stimule la bile et le drainage hépatique après des repas riches.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de romarin (1,5 g)",
      "1/2 c. à café de curcuma (1 g)",
      "1 c. à café de menthe poivrée (1 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Chauffer l'eau à 90 °C.",
      "Placer romarin, curcuma et menthe dans un filtre.",
      "Verser l'eau, couvrir et infuser 10 minutes.",
      "Filtrer soigneusement.",
      "Boire le matin à jeun, 20 minutes avant le petit-déjeuner."
    ],
    posologie: "1 tasse le matin à jeun pendant 10 jours.",
    conservation: "Mélange sec : 12 mois à l'abri de la lumière.",
    avertissement: "Contre-indiqué en cas d'obstruction biliaire."
  },
  {
    id: "digestion-apaisee",
    nom: "Digestion apaisée",
    objectif: "Ballonnements et spasmes digestifs",
    plantes: ["Camomille matricaire", "Menthe poivrée", "Fenouil"],
    effet: "Association classique après les repas : antispasmodique, carminative et apaisante.",
    temps: "5 min + 8 min d'infusion",
    ingredients: [
      "1 c. à soupe du mélange à parts égales (≈ 3 g) : fleurs de camomille matricaire, feuilles de menthe poivrée, graines de fenouil",
      "250 ml d'eau"
    ],
    preparation: [
      "Écraser légèrement les graines de fenouil au mortier pour libérer les arômes.",
      "Mélanger les trois plantes à parts égales.",
      "Porter l'eau à frémissement puis la verser sur 1 c. à soupe du mélange.",
      "Couvrir et laisser infuser 8 minutes.",
      "Filtrer et boire tiède."
    ],
    posologie: "1 tasse après chaque repas principal, jusqu'à 3 par jour.",
    conservation: "Mélange sec : 12 mois au sec. Infusion : consommer immédiatement.",
    avertissement: "Éviter la menthe en cas de reflux gastrique."
  },
  {
    id: "energie-et-remineralisation",
    nom: "Énergie et reminéralisation",
    objectif: "Fatigue et carences",
    plantes: ["Ortie", "Romarin", "Cassis"],
    effet: "Trio revitalisant riche en minéraux, soutient le tonus général.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à soupe de feuilles d'ortie (3 g)",
      "1 c. à café de romarin (1,5 g)",
      "1 c. à café de feuilles de cassis (1,5 g)",
      "400 ml d'eau",
      "quelques gouttes de jus de citron"
    ],
    preparation: [
      "Placer les plantes dans une théière préchauffée.",
      "Verser l'eau à 90 °C.",
      "Couvrir et infuser 10 minutes.",
      "Filtrer et ajouter le jus de citron (le fer végétal est mieux absorbé avec la vitamine C).",
      "Boire le matin ou en début d'après-midi."
    ],
    posologie: "1 à 2 tasses le matin, cure de 3 semaines.",
    conservation: "Éviter le soir (romarin tonique). Infusion : dans la journée.",
    avertissement: "Prudence en cas de traitement diurétique."
  },
  {
    id: "gorge-et-toux",
    nom: "Gorge et toux",
    objectif: "Maux de gorge et toux",
    plantes: ["Thym", "Réglisse", "Plantain lancéolé"],
    effet: "Antiseptique, adoucissant et anti-irritant pour les voies respiratoires.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de thym séché (1,5 g)",
      "1/2 c. à café de racine de réglisse (1 g)",
      "1 c. à café de plantain lancéolé (1,5 g)",
      "250 ml d'eau",
      "1 c. à café de miel de thym"
    ],
    preparation: [
      "Porter l'eau à frémissement.",
      "Verser sur les trois plantes et couvrir sans attendre.",
      "Infuser 10 minutes.",
      "Filtrer finement pour éviter les poils du plantain.",
      "Ajouter le miel une fois tiède, ou utiliser tiède en gargarisme de 30 secondes."
    ],
    posologie: "3 tasses par jour, ou 2 gargarismes par jour, pendant 5 jours.",
    conservation: "Ne pas dépasser 4 à 6 semaines de réglisse. Infusion : à boire dans la journée.",
    avertissement: "Réglisse interdite en cas d'hypertension."
  },
  {
    id: "serenite-de-la-menopause",
    nom: "Sérénité de la ménopause",
    objectif: "Bouffées de chaleur",
    plantes: ["Sauge officinale", "Aubépine", "Mélisse"],
    effet: "La sauge régule la sudation, l'aubépine et la mélisse calment les tensions nerveuses.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de sauge officinale (1,5 g)",
      "1 c. à café d'aubépine (1,5 g)",
      "1 c. à café de mélisse (1,5 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Mélanger les trois plantes à parts égales.",
      "Chauffer l'eau à 90 °C.",
      "Verser sur le mélange et couvrir.",
      "Infuser 10 minutes.",
      "Filtrer et boire tiède, matin et soir."
    ],
    posologie: "2 tasses par jour, 3 semaines par mois.",
    conservation: "Mélange sec : 12 mois. Infusion : à boire dans la journée.",
    avertissement: "Contre-indiquée en cas d'antécédent de cancer hormonodépendant."
  },
  {
    id: "trio-du-sommeil",
    nom: "Trio du sommeil",
    objectif: "Insomnie et réveils nocturnes",
    plantes: ["Valériane", "Passiflore", "Lavande vraie"],
    effet: "La valériane facilite l'endormissement, la passiflore calme le mental et la lavande détend le corps.",
    temps: "5 min de préparation + 10 min d'infusion",
    ingredients: [
      "1 c. à café de racine de valériane séchée (2 g)",
      "1 c. à café de parties aériennes de passiflore (1,5 g)",
      "1 c. à café de fleurs de lavande vraie (1 g)",
      "300 ml d'eau filtrée",
      "1 c. à café de miel (facultatif)"
    ],
    preparation: [
      "Porter les 300 ml d'eau à frémissement (environ 90 °C), sans bouillir à gros bouillons.",
      "Placer les trois plantes dans une théière ou un filtre à thé.",
      "Verser l'eau chaude sur le mélange et couvrir aussitôt pour retenir les huiles essentielles.",
      "Laisser infuser 10 minutes.",
      "Filtrer, sucrer au miel si souhaité et boire lentement."
    ],
    posologie: "1 tasse 30 minutes avant le coucher, en cure de 3 semaines maximum.",
    conservation: "Mélange sec : bocal hermétique à l'abri de la lumière, 12 mois. Infusion : à boire dans l'heure.",
    avertissement: "Somnolence : ne pas conduire. Éviter avec des somnifères."
  }
];

export const AVIS = "Ces informations sont données à titre indicatif et ne remplacent pas l'avis d'un médecin ou d'un pharmacien, notamment en cas de grossesse, de traitement en cours ou de maladie chronique.";

export const IMAGE_EXTENSIONS = {
  "aubepine": "jpg",
  "camomille-matricaire": "jpg",
  "cassis": "jpg",
  "curcuma": "jpg",
  "echinacee": "jpg",
  "fenouil": "jpg",
  "gingembre": "jpg",
  "lavande-vraie": "jpg",
  "melisse": "jpg",
  "menthe-poivree": "jpg",
  "millepertuis": "jpg",
  "ortie": "jpg",
  "passiflore": "jpg",
  "plantain-lanceole": "jpg",
  "reglisse": "jpg",
  "romarin": "jpg",
  "sauge-officinale": "jpg",
  "sureau-noir": "jpg",
  "thym": "jpg",
  "valeriane": "jpg"
};
