// Plantes supplémentaires — données phytothérapeutiques de référence (ESCOP, OMS, Wood).
// Champs : actifs (molécules clés), formes (galéniques), posologie, interactions, grossesse.
// Bienfaits alignés sur la taxonomie existante pour filtrage et carte des synergies.

export const PLANTES_SUP = [
  {
    id: "ail",
    nom: "Ail",
    latin: "Allium sativum",
    famille: "Amaryllidacées",
    image: null,
    emoji: "🧄",
    bienfaits: ["Cœur", "Tension artérielle", "Antiseptique", "Immunité"],
    parties: "Bulbe",
    usages: "Prévention cardiovasculaire, hypertension légère, infections respiratoires.",
    preparation: "Gousse crue écrasée, ou extrait sec standardisé en gélules.",
    actifs: "Alicine (alliine → alliinease), composés soufrés (ajoènes, sulfures).",
    formes: "Gélules d'extrait sec, teinture, bulbe cru cuit doucement.",
    posologie: "1 à 2 gousses crues par jour, ou 600–900 mg/j d'extrait sec standardisé.",
    interactions: "Potentialise les anticoagulants et antihypertenseurs ; arrêt 7 jours avant chirurgie.",
    grossesse: "Alimentaire OK ; doses thérapeutiques concentrées à éviter.",
    precaution: "Irritation gastrique possible à jeun ; prudence sous anticoagulants."
  },
  {
    id: "arbre-a-the",
    nom: "Arbre à thé",
    latin: "Melaleuca alternifolia",
    famille: "Myrtacées",
    image: null,
    emoji: "🫚",
    bienfaits: ["Antiseptique", "Cicatrisant", "Antiviral", "Anti-inflammatoire"],
    parties: "Feuilles (huile essentielle)",
    usages: "Acné, mycoses cutanées, plaies superficielles, verrues, ovulation buccale.",
    preparation: "Huile essentielle diluée à 5–10 % dans une huile végétale, usage externe.",
    actifs: "Terpinén-4-ol (≥ 30 %), γ-terpinène, α-terpinène, 1,8-cinéole (< 15 %).",
    formes: "Huile essentielle, savons, crèmes, pastilles pour la gorge.",
    posologie: "Usage externe : 1 à 2 gouttes HE pures possibles en points localisés, sinon diluée 5–10 % ; bain : 5 gouttes dispersées.",
    interactions: "Usage cutané : risque de sensibilisation si pur et répété.",
    grossesse: "Usage externe dilué possible ; prudence au 1er trimestre.",
    precaution: "NE JAMAIS AVALER l'huile essentielle (toxicité neurologique). Allergisant potentiel."
  },
  {
    id: "artichaut",
    nom: "Artichaut",
    latin: "Cynara scolymus",
    famille: "Astéracées",
    image: null,
    emoji: "🌿",
    bienfaits: ["Foie", "Digestion", "Drainage", "Cholestérol"],
    parties: "Feuilles",
    usages: "Digestion difficile, foie paresseux, cholestérol modérément élevé.",
    preparation: "Infusion de feuilles 10 min, ou extrait sec en gélules.",
    actifs: "Acides chlorogéniques, cynarine, flavonoïdes (lutéoline).",
    formes: "Infusion, extrait sec, jus de feuilles.",
    posologie: "2 à 3 tasses par jour avant les repas, ou 1,5 g/j d'extrait sec.",
    interactions: "Peut potentialiser les hypocholestérolémiants ; prudence avec les diurétiques.",
    grossesse: "Autorisée en usage alimentaire ; cures thérapeutiques déconseillées.",
    precaution: "Contre-indiqué en cas d'obstruction des voies biliaires ou allergie aux Astéracées."
  },
  {
    id: "ashwagandha",
    nom: "Ashwagandha",
    latin: "Withania somnifera",
    famille: "Solanacées",
    image: null,
    emoji: "🌱",
    bienfaits: ["Surrénales", "Anxiété", "Sommeil", "Tonique"],
    parties: "Racine",
    usages: "Stress chronique, fatigue surrénalienne, anxiété, insomnie d'endormissement.",
    preparation: "Poudre de racine en gelules, décoction 15 min avec lait (lait d'or).",
    actifs: "Withanolides (≥ 2,5 %), alcaloïdes somniférines, withaférine A.",
    formes: "Poudre de racine (churna), extrait sec standardisé (KSM-66, Sensoril).",
    posologie: "300–600 mg/j d'extrait standardisé, ou 3–6 g/j de poudre de racine, en cure de 4 à 12 semaines.",
    interactions: "Potentialise les sédatifs, immunosuppresseurs et thyroïdiens ; prudence avec les anxiolytiques.",
    grossesse: "CONTRE-INDIQUÉE (avortifuge documenté dans les études animales).",
    precaution: "Éviter en hyperthyroïdie, maladie auto-immune sans avis médical ; rares hépatites signalées."
  },
  {
    id: "bambou",
    nom: "Bambou (tabashir)",
    latin: "Bambusa vulgaris",
    famille: "Poacées",
    image: null,
    emoji: "🎋",
    bienfaits: ["Cheveux et ongles", "Reminéralisant", "Articulations", "Drainage"],
    parties: "Exsudat de tige (tabashir)",
    usages: "Fragilité capillaire et unguéale, déminéralisation, soutien du cartilage.",
    preparation: "Poudre de silice en gélules, associée à la vitamine C ou la prêle.",
    actifs: "Silice (70 % dans l'exsudat), minéraux traces.",
    formes: "Gélules de poudre, sirops capillaires.",
    posologie: "300 à 600 mg/j de silice en cure de 1 à 3 mois.",
    interactions: "Peut réduire l'absorption du thiamine (B1) en usage prolongé.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Boire suffisamment d'eau ; ne pas cumuler avec d'autres silices très concentrées."
  },
  {
    id: "bardane",
    nom: "Bardane",
    latin: "Arctium lappa",
    famille: "Astéracées",
    image: null,
    emoji: "🪴",
    bienfaits: ["Drainage", "Foie", "Cicatrisant", "Digestion"],
    parties: "Racine, Feuilles",
    usages: "Acné, eczéma, furoncles, peau grasse, drainage hépatique et rénal doux.",
    preparation: "Décoction de racine 10 min, 2 à 3 tasses par jour, cures de 3 semaines.",
    actifs: "Inuline (prébiotique), lignanes (arctiine), polyènes, mucilages.",
    formes: "Décoction, teinture-mère, capsule de racine séchée.",
    posologie: "2 à 3 g/j de racine sèche en décoction, ou 2 ml de teinture 3 fois par jour.",
    interactions: "Peut potentialiser les diurétiques et hypoglycémiants.",
    grossesse: "Déconseillée (effet utérotonique possible de la racine).",
    precaution: "Bien s'hydrater ; contre-indiquée en obstruction biliaire."
  },
  {
    id: "bougain",
    nom: "Bouleau",
    latin: "Betula pendula",
    famille: "Bétulacées",
    image: null,
    emoji: "🌳",
    bienfaits: ["Drainage", "Diurétique", "Articulations", "Circulation"],
    parties: "Feuilles, Sève",
    usages: "Drainage rénal, rétention d'eau, cystites récidivantes, arthrose.",
    preparation: "Infusion de feuilles 10 min ; sève fraîche en cure de 3 semaines au printemps.",
    actifs: "Flavonoïdes (hyperoside, quercitrine), saponines, huile essentielle (sécoiridoïdes).",
    formes: "Infusion, jus de sève, extrait fluide, gélules.",
    posologie: "2 à 3 tasses par jour, ou 100–150 ml de sève par jour en cure.",
    interactions: "Potentialise les diurétiques ; espacer de la prise de lithium.",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Déconseillée en cas d'œdème cardiaque ou rénal sévère (apport hydrique)."
  },
  {
    id: "bourrache",
    nom: "Bourrache",
    latin: "Borago officinalis",
    famille: "Boraginacées",
    image: null,
    emoji: "🌸",
    bienfaits: ["Surrénales", "Drainage", "Cicatrisant", "Peau"],
    parties: "Fleurs, Huile de graines",
    usages: "Fatigue surrénalienne, peau sèche, eczéma, stress, allaitement (galactogène doux).",
    preparation: "Infusion de fleurs 10 min ; huile de bourrache en capsules, à froid.",
    actifs: "Mucilages, acide gamma-linolénique (AGL 20–25 % dans l'huile), nitrosamines potentielles.",
    formes: "Infusion de fleurs, capsules d'huile, macérat huileux.",
    posologie: "1 à 2 tasses par jour de fleurs ; 1 à 2 g/j d'huile de bourrache (AGL).",
    interactions: "Peut potentialiser les anticoagulants (huile riche en AGL).",
    grossesse: "Infusion ponctuelle OK ; huile déconseillée (risque théorique de contractions).",
    precaution: "Les parties vertes contiennent des alcaloïdes pyrrolizidiniques : limiter aux fleurs et à l'huile testée."
  },
  {
    id: "camomille-romaine",
    nom: "Camomille romaine",
    latin: "Chamaemelum nobile",
    famille: "Astéracées",
    image: null,
    emoji: "🌼",
    bienfaits: ["Digestion", "Anxiété", "Antispasmodique", "Peau"],
    parties: "Fleurs",
    usages: "Spasmes digestifs, stress, migraines nerveuses, rougeurs cutanées.",
    preparation: "Infusion 10 min à couvert ; HE diluée en massage du plexus.",
    actifs: "Esters d'angélate (leucodispasmodique), α-bisabolol, camazulène.",
    formes: "Infusion, HE, hydrolat (eau de camomille).",
    posologie: "1 à 3 tasses par jour ; HE : 1 goutte sur sucre ou en massage diluée 10 %.",
    interactions: "Potentialise les sédatifs et anticoagulants à forte dose.",
    grossesse: "Infusion modérée OK ; HE déconseillée (éménagogue).",
    precaution: "Allergie croisée possible avec les Astéracées (marguerite, arnica)."
  },
  {
    id: "canneberge",
    nom: "Canneberge",
    latin: "Vaccinium macrocarpon",
    famille: "Éricacées",
    image: null,
    emoji: "🫐",
    bienfaits: ["Diurétique", "Antiseptique", "Immunité", "Circulation"],
    parties: "Fruit",
    usages: "Prévention des cystites à E. coli, santé urinaire, antioxydant.",
    preparation: "Jus non sucré 300 ml/j, ou extrait sec standardisé en PAC.",
    actifs: "Proanthocyanidines de type A (PAC 36 mg/j dose active), fructose, acides organiques.",
    formes: "Jus, poudre de fruit, gélules d'extrait standardisé.",
    posologie: "36 mg/j de PAC (≈ 2 g/j d'extrait) en prévention, cures de 4 à 12 semaines.",
    interactions: "Prudence avec la warfarine (surveillance INR).",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Ne remplace pas un antibiotique en cystite installée avec fièvre."
  },
  {
    id: "cypres",
    nom: "Cyprès toujours vert",
    latin: "Cupressus sempervirens",
    famille: "Cupressacées",
    image: null,
    emoji: "🌲",
    bienfaits: ["Circulation", "Drainage", "Antispasmodique", "Toux"],
    parties: "Cônes, Feuilles",
    usages: "Insuffisance veineuse, jambes lourdes, toux sèche spasmodique, hémorroïdes.",
    preparation: "HE en massage des jambes (diluée 10 %), teinture de cônes.",
    actifs: "Pinène, camphène, cédrène (HE) ; procyanidines (cônes).",
    formes: "HE, teinture-mère, gélules d'extrait de cône.",
    posologie: "HE : 2 gouttes 2 fois par jour sur sucre ou diluée en massage ; teinture : 20 gouttes matin et soir.",
    interactions: "Prudence avec les antihypertenseurs (effet veinotonique).",
    grossesse: "HE déconseillée par voie orale.",
    precaution: "Allergie aux Cupressacées fréquente (pollens)."
  },
  {
    id: "dgl",
    nom: "Réglisse DGL (déglycyrrhizinée)",
    latin: "Glycyrrhiza glabra (DGL)",
    famille: "Fabacées",
    image: null,
    emoji: "🪵",
    bienfaits: ["Estomac", "Cicatrisant", "Anti-inflammatoire", "Digestion"],
    parties: "Racine traitée",
    usages: "Ulcère gastrique, reflux, gastrite — sans l'effet hypertenseur de la glycyrrhizine.",
    preparation: "Comprimés à mâcher 20 min avant les repas.",
    actifs: "Flavonoïdes (licochalcone), mucilages ; glycyrrhizine < 3 %.",
    formes: "Comprimés à mâcher DGL, poudre.",
    posologie: "380 mg avant chaque repas et au coucher (2 à 4 comprimés par jour).",
    interactions: "Aucune significative (glycyrrhizine quasi absente).",
    grossesse: "Autorisée — forme DGL sûre pour l'estomac pendant la grossesse.",
    precaution: "Ne pas confondre avec la réglisse classique (hypertension)."
  },
  {
    id: "echinacee-pale",
    nom: "Échinacée pâle",
    latin: "Echinacea pallida",
    famille: "Astéracées",
    image: null,
    emoji: "🌺",
    bienfaits: ["Immunité", "Antiviral", "Infections ORL", "Cicatrisant"],
    parties: "Racine",
    usages: "Rhume, sinusite, prévention hivernale — complément de l'E. purpurea.",
    preparation: "Teinture-mère ou extrait sec, en cures courtes de 10 jours.",
    actifs: "Échinacoside, polysaccharides, alkylamides.",
    formes: "Teinture-mère, gélules d'extrait sec.",
    posologie: "40 à 60 gouttes de teinture 3 fois par jour au début de l'infection, pendant 5 à 10 jours.",
    interactions: "Contre-indiquée avec les immunosuppresseurs.",
    grossesse: "Autorisée en cures courtes sous avis (ESCOP la valide).",
    precaution: "Maladie auto-immune : éviter sans avis médical."
  },
  {
    id: "eleutherocoque",
    nom: "Éleuthérocoque",
    latin: "Eleutherococcus senticosus",
    famille: "Araliacées",
    image: null,
    emoji: "🌾",
    bienfaits: ["Surrénales", "Tonique", "Mémoire", "Immunité"],
    parties: "Racine",
    usages: "Fatigue chronique, stress prolongé, concentration, convalescence.",
    preparation: "Teinture-mère, extrait sec standardisé en gélules.",
    actifs: "Éleuthéroside B, E (≥ 0,8 %), phénylpropanoïdes, coumarines.",
    formes: "Gélules d'extrait standardisé, teinture.",
    posologie: "600 à 1 200 mg/j d'extrait sec standardisé, le matin, cures de 3 à 6 semaines.",
    interactions: "Prudence avec digoxine, antidiabétiques et antihypertenseurs.",
    grossesse: "Déconseillé sans avis.",
    precaution: "Peut provoquer insomnia si pris le soir ; hypertension instable : avis médical."
  },
  {
    id: "eucalyptus",
    nom: "Eucalyptus radié",
    latin: "Eucalyptus radiata",
    famille: "Myrtacées",
    image: null,
    emoji: "🍃",
    bienfaits: ["Décongestionnant", "Antiseptique", "Toux", "Immunité"],
    parties: "Feuilles (huile essentielle)",
    usages: "Rhinite, sinusite, bronchite, congestion nasale, inhalations.",
    preparation: "Inhalation : 3 gouttes HE dans un bol d'eau chaude 10 min, yeux fermés.",
    actifs: "1,8-cinéole (60–75 %), α-terpinéol, viridiflorol.",
    formes: "HE (inhalation, diffusion), suppositoires, pastilles.",
    posologie: "Inhalation 2 fois par jour en phase aiguë ; diffusion max 30 min.",
    interactions: "Peut induire les enzymes hépatiques (CYP3A4).",
    grossesse: "Déconseillée par voie orale ; inhalation OK après le 1er trimestre.",
    precaution: "HE toxique par voie orale à haute dose ; asthme : tester au préalable."
  },
  {
    id: "fenugrec",
    nom: "Fenugrec",
    latin: "Trigonella foenum-graecum",
    famille: "Fabacées",
    image: null,
    emoji: "🌾",
    bienfaits: ["Lactation", "Digestion", "Tonique", "Cholestérol"],
    parties: "Graines",
    usages: "Stimulation de la lactation, anorexie, convalescence, glycémie.",
    preparation: "Graines germées, poudre en capsules, infusion 3 g/tasse.",
    actifs: "Saponines stéroïdennes (diosgénine), 4-hydroxyisoleucine, mucilages.",
    formes: "Poudre de graines, gélules, huile.",
    posologie: "2 à 5 g de graines par jour, en 2 à 3 prises, pour la lactation.",
    interactions: "Potentialise les antidiabétiques et anticoagulants.",
    grossesse: "CONTRE-INDIQUÉE (effet utérotonique).",
    precaution: "Goût d'érable des sueurs ; prudence hypoglycémie."
  },
  {
    id: "ginkgo",
    nom: "Ginkgo biloba",
    latin: "Ginkgo biloba",
    famille: "Ginkgoacées",
    image: null,
    emoji: "🍂",
    bienfaits: ["Mémoire", "Circulation", "Antioxydant", "Nerfs"],
    parties: "Feuilles",
    usages: "Troubles de la mémoire, acouphènes, artériopathie, vertiges.",
    preparation: "Extrait standardisé (EGb 761) en gélules ou solution buvable.",
    actifs: "Flavonoïdes (quercétine, kaempférol), terpènes trilactoniques (ginkgolides, bilobalide).",
    formes: "Extrait standardisé 24 % flavones glycosides / 6 % terpènes.",
    posologie: "120 à 240 mg/j d'extrait standardisé, en cure de 2 à 3 mois.",
    interactions: "MAJEUR : potentialise anticoagulants et antiagrégants (aspirine, AINS) ; réduire si épilepsie traitée.",
    grossesse: "Déconseillé (données insuffisantes).",
    precaution: "Arrêt 4 jours avant chirurgie ; céphalées possibles en début de cure."
  },
  {
    id: "ginseng",
    nom: "Ginseng",
    latin: "Panax ginseng",
    famille: "Araliacées",
    image: null,
    emoji: "🫚",
    bienfaits: ["Tonique", "Surrénales", "Mémoire", "Immunité"],
    parties: "Racine",
    usages: "Fatigue physique et intellectuelle, convalescence, performance cognitive.",
    preparation: "Racine en décoction 30 min, extrait rouge standardisé en gélules.",
    actifs: "Ginsénosides (≥ 4 % Rg1+Rb1), polysaccharides, polyacétylènes.",
    formes: "Extrait rouge standardisé (Korean Red), racine sèche, sirop.",
    posologie: "200 à 400 mg/j d'extrait standardisé, le matin, cures de 2 à 3 semaines puis pause d'une semaine.",
    interactions: "Prudence avec warfarine (surveillance INR), antidiabétiques et IMMAO.",
    grossesse: "Déconseillé.",
    precaution: "Hypertension non contrôlée et insomnie : éviter ; prendre le matin."
  },
  {
    id: "guimauve",
    nom: "Guimauve",
    latin: "Althaea officinalis",
    famille: "Malvacées",
    image: null,
    emoji: "🪻",
    bienfaits: ["Estomac", "Toux", "Cicatrisant", "Digestion"],
    parties: "Racine, Feuilles",
    usages: "Gastrite, reflux, toux sèche irritative, constipation, irritation buccale.",
    preparation: "Macérat à froid 2 h (mucilages fragiles à la chaleur), puis boire.",
    actifs: "Mucilages (racine 25–35 %), flavonoïdes, pectines.",
    formes: "Sirop, macérat froid, poudre, pastilles.",
    posologie: "2 à 5 g de racine par jour en macérat froid ; sirop : 1 c. à soupe 3 fois par jour.",
    interactions: "Espace 2 h avec la prise de médicaments (barrière muqueuse).",
    grossesse: "Autorisée — très bien tolérée.",
    precaution: "Prise à distance des traitements (diminue leur absorption)."
  },
  {
    id: "harpagophytum",
    nom: "Harpagophytum (griffe du diable)",
    latin: "Harpagophytum procumbens",
    famille: "Pédaliacées",
    image: null,
    emoji: "🪝",
    bienfaits: ["Articulations", "Anti-inflammatoire", "Drainage", "Digestion"],
    parties: "Tubercules secondaires",
    usages: "Arthrose, lombalgies, tendinites, douleurs articulaires chroniques.",
    preparation: "Extrait sec standardisé en gélules, décoction amère de tubercule.",
    actifs: "Harpagoside (≥ 1,2 % norme française), harpagide, β-sitostérol.",
    formes: "Extrait sec standardisé, poudre de tubercule.",
    posologie: "1,2 à 2 g/j d'extrait sec standardisé (≈ 50 mg d'harpagoside), en cure de 2 à 3 mois.",
    interactions: "Prudence avec les anticoagulants, anti-hypertenseurs et hypoglycémiants.",
    grossesse: "CONTRE-INDIQUÉ (effet utérotonique).",
    precaution: "Goût très amer ; douleurs gastriques possibles : prendre au milieu des repas."
  },
  {
    id: "lierre-terrestre",
    nom: "Lierre terrestre",
    latin: "Glechoma hederacea",
    famille: "Lamiacées",
    image: null,
    emoji: "🍀",
    bienfaits: ["Drainage", "Digestion", "Antiseptique", "Toux"],
    parties: "Parties aériennes",
    usages: "Bronchite, drainage rénal, gastrite, cicatrisation cutanée.",
    preparation: "Infusion 10 min, 2 tasses par jour, cures courtes de 10 jours.",
    actifs: "Huile essentielle (pulegone minoritaire), flavonoïdes, triterpènes.",
    formes: "Infusion, sirop.",
    posologie: "1 à 2 tasses par jour pendant 10 jours maximum.",
    interactions: "Pas d'interaction majeure connue.",
    grossesse: "Déconseillé (doses élevées potentiellement abortives).",
    precaution: "Limiter aux cures courtes (présence de pulegone en trace)."
  },
  {
    id: "mauve",
    nom: "Mauve",
    latin: "Malva sylvestris",
    famille: "Malvacées",
    image: null,
    emoji: "💜",
    bienfaits: ["Estomac", "Digestion", "Toux", "Cicatrisant"],
    parties: "Fleurs, Feuilles",
    usages: "Constipation légère, irritation digestive et respiratoire, toux sèche, peau irritée.",
    preparation: "Infusion 10 min de fleurs et feuilles, 2 à 3 tasses par jour.",
    actifs: "Mucilages (feuilles 6–10 %), anthocyanes (malvidine), tanins.",
    formes: "Infusion, sirop, cataplasme de feuilles.",
    posologie: "2 à 3 tasses par jour ; cataplasme de feuilles chaudes sur peaux irritées.",
    interactions: "Espace 2 h avec les médicaments.",
    grossesse: "Autorisée.",
    precaution: "Très bien tolérée ; effet laxatif doux possible."
  },
  {
    id: "oregon-grape",
    nom: "Mahonia (Oregon grape)",
    latin: "Mahonia aquifolium",
    famille: "Bérberidacées",
    image: null,
    emoji: "🫐",
    bienfaits: ["Peau", "Drainage", "Foie", "Antiseptique"],
    parties: "Écorce de racine",
    usages: "Psoriasis, eczéma sec, acné inflammatoire, drainage hépatique.",
    preparation: "Teinture-mère, crème à 10 % d'extrait d'écorce en usage externe.",
    actifs: "Berbérine, berbamine, oxyacanthine (alcaloïdes isoquinoléiques).",
    formes: "Teinture-mère, crème, gélules d'extrait sec.",
    posologie: "20 à 40 gouttes de teinture 2 fois par jour ; crème 2 applications par jour.",
    interactions: "La berbérine déplace la bilirubine : prudence sous traitement hépatique.",
    grossesse: "CONTRE-INDIQUÉE (alcaloïdes utérotoniques).",
    precaution: "Usage interne limité à 3 semaines ; supervision conseillée."
  },
  {
    id: "pissenlit",
    nom: "Pissenlit",
    latin: "Taraxacum officinale",
    famille: "Astéracées",
    image: null,
    emoji: "☀️",
    bienfaits: ["Drainage", "Foie", "Diurétique", "Digestion"],
    parties: "Racine, Feuilles",
    usages: "Drainage hépatique et rénal, digestion lente, rétention d'eau, cholestérol.",
    preparation: "Décoction de racine 10 min (hépatique), infusion de feuilles 10 min (rénal).",
    actifs: "Inuline, taraxastérol, acides chlorogéniques, potassium (feuilles).",
    formes: "Décoction, infusion, extrait sec, jeunes feuilles en salade.",
    posologie: "3 à 4 g/j de racine en décoction, ou 2 tasses de feuilles par jour.",
    interactions: "Prudence avec lithium (diurèse), antibiotiques quinolones.",
    grossesse: "Autorisée aux doses alimentaires ; cures à avis.",
    precaution: "Obstruction biliaire : contre-indiqué ; allergie aux Astéracées possible."
  },
  {
    id: "reine-des-pres",
    nom: "Reine-des-prés",
    latin: "Filipendula ulmaria",
    famille: "Rosacées",
    image: null,
    emoji: "🤍",
    bienfaits: ["Anti-inflammatoire", "Articulations", "Drainage", "Digestion"],
    parties: "Sommités fleuries",
    usages: "Arthrose, rhumatismes inflammatoires, fièvre légère, cellulite.",
    preparation: "Infusion 10 min à couvert (ne pas faire bouillir), 2 à 3 tasses par jour.",
    actifs: "Dérivés salicylés (salicylate de méthyle, hélicine), flavonoïdes, tanins.",
    formes: "Infusion, teinture-mère, gélules.",
    posologie: "2 à 3 g de sommités fleuries par tasse, 3 fois par jour.",
    interactions: "Potentialise les anticoagulants et antiagrégants (comme l'aspirine).",
    grossesse: "CONTRE-INDIQUÉE (dérivés salicylés).",
    precaution: "Allergie à l'aspirine : interdite."
  },
  {
    id: "sarrisaparrilla",
    nom: "Salsepareille",
    latin: "Smilax officinalis",
    famille: "Smilacacées",
    image: null,
    emoji: "🌿",
    bienfaits: ["Drainage", "Peau", "Anti-inflammatoire", "Tonique"],
    parties: "Racine",
    usages: "Psoriasis, eczéma, acné, drainage cutané, fatigue chronique.",
    preparation: "Décoction de racine 15 min, 2 tasses par jour, cures de 3 semaines.",
    actifs: "Saponines stéroïdennes (sarsasaponine, smilasaponine), phytostérols.",
    formes: "Décoction, teinture-mère, gélules.",
    posologie: "1,5 à 3 g/j de racine en décoction.",
    interactions: "Potentialise les digitaliques et bêtabloquants (théorie historique).",
    grossesse: "Déconseillée.",
    precaution: "Irritation gastrique possible ; bien hydrater."
  },
  {
    id: "verbena-citronnee",
    nom: "Verveine citronnée",
    latin: "Aloysia citrodora",
    famille: "Verbénacées",
    image: null,
    emoji: "🍋",
    bienfaits: ["Digestion", "Anxiété", "Sommeil", "Antispasmodique"],
    parties: "Feuilles",
    usages: "Stress digestif, ballonnements nerveux, insomnie légère, spasmophilie.",
    preparation: "Infusion 10 min à couvert, après les repas et le soir.",
    actifs: "Huile essentielle (citral 30–35 %, géraniol), verbascoside, lutéoline.",
    formes: "Infusion, HE, hydrolat.",
    posologie: "2 à 3 tasses par jour ; HE : 1 goutte sur sucre au besoin.",
    interactions: "Potentialise les sédatifs à forte dose.",
    grossesse: "Autorisée en infusion modérée.",
    precaution: "Photosensibilisation cutanée possible avec l'HE."
  },
  {
    id: "vigne-rouge",
    nom: "Vigne rouge",
    latin: "Vitis vinifera",
    famille: "Vitacées",
    image: null,
    emoji: "🍇",
    bienfaits: ["Circulation", "Antioxydant", "Drainage", "Peau"],
    parties: "Feuilles, Pépins",
    usages: "Jambes lourdes, varices, hémorroïdes, couperose, antioxydant global.",
    preparation: "Infusion de feuilles 10 min, extrait de pépins standardisé en gélules.",
    actifs: "Anthocyanes (feuilles), OPC (proanthocyanidines oligomères 95 % pépins).",
    formes: "Infusion, extrait sec de pépins, jus de raisin noir.",
    posologie: "150 à 300 mg/j d'extrait de pépins standardisé (OPC), en cure de 2 à 3 mois.",
    interactions: "Prudence avec les anticoagulants (OPC à fortes doses).",
    grossesse: "Autorisée aux doses usuelles.",
    precaution: "Rien de notable aux doses normales."
  }
];

export const ASSOCIATIONS_SUP = [
  {
    id: "antivol-arteriel",
    nom: "Bouclier artériel",
    objectif: "Cholestérol et santé cardiovasculaire",
    plantes: ["Ail", "Artichaut", "Vigne rouge"],
    effet: "Réduit l'absorption intestinale du cholestérol, protège l'endothélium et fluidifie le sang.",
    temps: "5 min + 10 min d'infusion",
    ingredients: [
      "1 gousse d'ail frais écrasée (à ajouter crue à la fin)",
      "1 c. à café de feuilles d'artichaut (1,5 g)",
      "1 c. à café de feuilles de vigne rouge (1,5 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Infuser artichaut et vigne rouge 10 minutes à couvert.",
      "Filtrer et laisser tiédir à 50 °C.",
      "Ajouter l'ail écrasé hors du feu (l'allicine est détruite au-delà de 60 °C).",
      "Boire immédiatement, de préférence le soir."
    ],
    posologie: "1 tasse par soir pendant 3 semaines, renouvelable après une pause d'une semaine.",
    conservation: "Mélange sec : 12 mois. Préparation : à boire dans la journée.",
    avertissement: "Prudence sous anticoagulants ; avis médical si hypotension traitée."
  },
  {
    id: "calme-surrrenal",
    nom: "Résilience surrénalienne",
    objectif: "Burn-out léger et fatigue chronique",
    plantes: ["Ashwagandha", "Éleuthérocoque", "Réglisse"],
    effet: "Soutient la réponse au stress (axe HPA), redonne tonus le matin et calme le soir.",
    temps: "5 min + 15 min de décoction",
    ingredients: [
      "1 c. à café de racine d'ashwagandha en poudre (2 g)",
      "1 c. à café de racine d'éleuthérocoque (2 g)",
      "1/2 c. à café de racine de réglisse (1 g)",
      "250 ml d'eau",
      "1 pincée de cannelle"
    ],
    preparation: [
      "Porter l'eau à frémissement avec l'éleuthérocoque et la réglisse.",
      "Décocter 15 minutes à couvert.",
      "Retirer du feu et incorporer l'ashwagandha en poudre.",
      "Couvrir et laisser infuser 5 minutes.",
      "Filtrer, ajouter la cannelle, boire le matin."
    ],
    posologie: "1 tasse le matin pendant 4 semaines maximum, puis 2 semaines de pause.",
    conservation: "Préparation : 24 h au frais. Cures courtes obligatoires (réglisse).",
    avertissement: "Contre-indiqué : hypertension, grossesse, hyperthyroïdie, corticoïdes."
  },
  {
    id: "foie-fier",
    nom: "Foie en fête",
    objectif: "Cure hépatique saisonnière",
    plantes: ["Pissenlit", "Artichaut", "Romarin", "Bardane"],
    effet: "Stimule la production et l'évacuation de la bile, protège les hépatocytes.",
    temps: "5 min + 15 min de décoction",
    ingredients: [
      "1 c. à café de racine de pissenlit (2 g)",
      "1 c. à café de feuilles d'artichaut (1,5 g)",
      "1 c. à café de romarin (1,5 g)",
      "1/2 c. à café de racine de bardane (1 g)",
      "400 ml d'eau"
    ],
    preparation: [
      "Mettre pissenlit et bardane (racines) dans l'eau froide.",
      "Porter à ébullition et décocter 10 minutes.",
      "Retirer du feu, ajouter artichaut et romarin.",
      "Couvrir et infuser 5 minutes.",
      "Filtrer et boire réparti sur la journée, de préférence avant les repas."
    ],
    posologie: "2 tasses par jour pendant 3 semaines, au changement de saison.",
    conservation: "Mélange sec : 12 mois. Décoction : 24 h au frais.",
    avertissement: "Contre-indiqué en cas d'obstruction biliaire ou de calculs encombrants."
  },
  {
    id: "gorge-herisse",
    nom: "Gorge apaisée",
    objectif: "Toux sèche et irritation ORL",
    plantes: ["Guimauve", "Mauve", "Réglisse"],
    effet: "Mucilages et adoucissants forment un film protecteur sur les muqueuses irritées.",
    temps: "5 min + 2 h de macération à froid",
    ingredients: [
      "1 c. à café de racine de guimauve (2 g)",
      "1 c. à soupe de fleurs et feuilles de mauve (2 g)",
      "1/2 c. à café de racine de réglisse (1 g)",
      "300 ml d'eau à température ambiante"
    ],
    preparation: [
      "Placer les trois plantes dans l'eau froide.",
      "Laisser macérer 2 heures à température ambiante (les mucilages n'aiment pas la chaleur).",
      "Filtrer et boire tiède ou à température ambiante.",
      "En cas de toux nocturne : ajouter 1 c. à café de miel de thym."
    ],
    posologie: "2 à 3 tasses par jour pendant la durée de l'irritation, 5 jours maximum pour la réglisse.",
    conservation: "Macérat : 24 h au réfrigérateur.",
    avertissement: "Réglisse interdite en cas d'hypertension ; à distance (2 h) des médicaments."
  },
  {
    id: "jambes-legeres",
    nom: "Jambes légères",
    objectif: "Insuffisance veineuse et jambes lourdes",
    plantes: ["Vigne rouge", "Cyprès toujours vert", "Mélisse"],
    effet: "Veinotonique et antioxydant, réduit la sensation de lourdeur et les œdèmes fins.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de feuilles de vigne rouge (1,5 g)",
      "1 c. à café de cônes de cyprès (1,5 g)",
      "1/2 c. à café de feuilles de mélisse (0,75 g)",
      "350 ml d'eau"
    ],
    preparation: [
      "Chauffer l'eau à 90 °C.",
      "Verser sur le mélange et couvrir.",
      "Infuser 10 minutes.",
      "Filtrer et boire le matin, éventuellement en bouteille emportée dans la journée."
    ],
    posologie: "1 à 2 tasses par jour en cure de 3 semaines, en complément de douches froides sur les jambes.",
    conservation: "Mélange sec : 12 mois. Infusion : dans la journée.",
    avertissement: "Prudence sous antihypertenseurs ; compléter par du mouvement."
  },
  {
    id: "menopause-serenite",
    nom: "Ménopause sereine",
    objectif: "Bouffées de chaleur et irritabilité",
    plantes: ["Sauge officinale", "Mélisse", "Verveine citronnée"],
    effet: "Module la thermorégulation, apaise le système nerveux et l'humeur.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de sauge officinale (1,5 g)",
      "1 c. à café de mélisse (1,5 g)",
      "1 c. à café de verveine citronnée (1 g)",
      "300 ml d'eau"
    ],
    preparation: [
      "Chauffer l'eau à 90 °C.",
      "Verser sur le mélange et couvrir immédiatement.",
      "Infuser 10 minutes.",
      "Filtrer et boire tiède, matin et soir."
    ],
    posologie: "2 tasses par jour, 3 semaines par mois.",
    conservation: "Mélange sec : 12 mois.",
    avertissement: "Sauge contre-indiquée en cas d'antécédent de cancer hormonodépendant."
  },
  {
    id: "peau-nette",
    nom: "Peau nette",
    objectif: "Acné et problèmes de peau",
    plantes: ["Bardane", "Mahonia (Oregon grape)", "Pissenlit"],
    effet: "Trio depuratif qui draine le foie et la peau par l'intérieur.",
    temps: "5 min + 15 min de décoction",
    ingredients: [
      "1 c. à café de racine de bardane (2 g)",
      "20 gouttes de teinture de mahonia (à ajouter filtré)",
      "1 c. à café de racine de pissenlit (2 g)",
      "400 ml d'eau"
    ],
    preparation: [
      "Décocter bardane et pissenlit 15 minutes à couvert.",
      "Filtrer, laisser tiédir.",
      "Ajouter la teinture de mahonia hors du feu.",
      "Boire en 2 prises dans la journée."
    ],
    posologie: "Cure de 3 semaines maximum, renouvelable après une semaine de pause.",
    conservation: "Décoction : 24 h au frais.",
    avertissement: "Mahonia contre-indiqué pendant la grossesse ; usage interne limité à 3 semaines."
  },
  {
    id: "respiration-libre",
    nom: "Respiration libre",
    objectif: "Bronchite et congestion respiratoire",
    plantes: ["Eucalyptus radié", "Thym", "Lierre terrestre"],
    effet: "Décongestionne les bronches, fluidifie les sécrétions et assainit l'airway.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "1 c. à café de thym (1,5 g)",
      "1 c. à café de lierre terrestre (1 g)",
      "1 goutte d'HE d'eucalyptus radié (dans un inhalateur ou sur un mouchoir)",
      "300 ml d'eau"
    ],
    preparation: [
      "Infuser thym et lierre terrestre 10 minutes à couvert.",
      "Filtrer, boire chaud lentement.",
      "En parallèle : inhalation de 3 gouttes d'HE d'eucalyptus dans un bol d'eau chaude, 10 minutes, yeux fermés."
    ],
    posologie: "2 tasses par jour et 1 à 2 inhalations par jour, pendant 5 à 7 jours.",
    conservation: "Mélange sec : 12 mois. HE : à l'abri de la lumière.",
    avertissement: "HE d'eucalyptus : interdite chez l'enfant de moins de 6 ans et l'asthmatique non testé."
  },
  {
    id: "systeme-immunitaire",
    nom: "Bouclier immunitaire complet",
    objectif: "Prévention des infections hivernales",
    plantes: ["Échinacée", "Sureau noir", "Gingembre", "Thym"],
    effet: "Stimule l'immunité innée, antiviral et sudorifique, assainit les muqueuses.",
    temps: "5 min + 20 min de cuisson/infusion",
    ingredients: [
      "1 c. à café de racine d'échinacée (2 g)",
      "1 c. à café de baies de sureau noir (2 g)",
      "2 g de gingembre frais râpé",
      "1 c. à café de thym (1 g)",
      "400 ml d'eau",
      "1 c. à café de miel de thym"
    ],
    preparation: [
      "Décocter gingembre et échinacée 10 minutes à couvert.",
      "Retirer du feu, ajouter sureau et thym.",
      "Infuser 10 minutes hors du feu.",
      "Filtrer, ajouter le miel tiède."
    ],
    posologie: "2 à 3 tasses par jour dès les premiers signes, pendant 5 à 7 jours.",
    conservation: "Préparation : 24 h au réfrigérateur.",
    avertissement: "Échinacée déconseillée en maladie auto-immune ; sureau toujours cuit."
  },
  {
    id: "urinaire-apaisee",
    nom: "Voies urinaires sereines",
    objectif: "Cystite légère et prévention urinaire",
    plantes: ["Canneberge", "Bouleau", "Mauve"],
    effet: "Antiadhésif sur E. coli, diurétique doux et apaisant pour la vessie irritée.",
    temps: "3 min + 10 min d'infusion",
    ingredients: [
      "2 g d'extrait de canneberge en PAC (36 mg), ou 100 ml de jus non sucré",
      "1 c. à café de feuilles de bouleau (1,5 g)",
      "1 c. à soupe de fleurs de mauve (2 g)",
      "400 ml d'eau"
    ],
    preparation: [
      "Infuser bouleau et mauve 10 minutes.",
      "Filtrer et laisser tiédir.",
      "Ajouter l'extrait de canneberge ou le jus hors du feu.",
      "Boire réparti sur la journée."
    ],
    posologie: "En prévention : 1 préparation par jour, cures de 4 à 12 semaines. En cas de fièvre ou de sang : consulter.",
    conservation: "Préparation : 24 h au frais.",
    avertissement: "Ne remplace pas une antibiothérapie en cystite installée avec fièvre."
  }
];
